import {database,one,stmt,insert,uid} from './db';
import {member,permit,audit,type Context} from './service';
import {can,DomainError,today} from './domain';
const hex=(b:ArrayBuffer|Uint8Array)=>Array.from(new Uint8Array(b)).map(n=>n.toString(16).padStart(2,'0')).join('');
const hash=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
export async function issueQr(c:Context,id:string){if(c.access.role!=='member'&&!can(c.access.role,'attendance',true))throw new DomainError('دسترسی مجاز نیست.',403);await member(c,id);const token=hex(crypto.getRandomValues(new Uint8Array(32))),expires=Date.now()+300000;
 await database().batch([stmt('UPDATE qr_tokens SET used_at=? WHERE tenant_id=? AND member_id=? AND used_at IS NULL',[uid(),c.tenant.id,id]),insert('qr_tokens',{id:uid(),tenant_id:c.tenant.id,member_id:id,token_hash:await hash(token),expires_at:expires})]);return {token:'FITSPACE:'+token,expires};}
export async function consumeQr(c:Context,input:string){permit(c,'attendance',true);const token=input.replace(/^FITSPACE:/,'').trim();if(!/^[a-f0-9]{64}$/.test(token))throw new DomainError('کد ورود معتبر نیست.');const th=await hash(token),row=await one('SELECT * FROM qr_tokens WHERE tenant_id=? AND token_hash=?',[c.tenant.id,th]);if(!row||row.used_at||row.expires_at<=Date.now())throw new DomainError('کد منقضی یا استفاده شده است.');const m=await member(c,row.member_id),day=today(c.tenant.timezone),claim=uid(),id=uid();
 const active=await one("SELECT id FROM memberships WHERE tenant_id=? AND member_id=? AND status='ACTIVE' AND start_date<=? AND end_date>=?",[c.tenant.id,m.id,day,day]);if(m.status!=='ACTIVE'||!active)throw new DomainError('عضویت فعال برای ورود لازم است.');
 const result=await database().batch([stmt('UPDATE qr_tokens SET used_at=? WHERE tenant_id=? AND token_hash=? AND used_at IS NULL AND expires_at>?',[claim,c.tenant.id,th,Date.now()]),stmt("INSERT INTO attendance(id,tenant_id,member_id,branch_id,day,method) SELECT ?,?,?,?,?,'QR' WHERE EXISTS(SELECT 1 FROM qr_tokens WHERE tenant_id=? AND token_hash=? AND used_at=?)",[id,c.tenant.id,m.id,m.branch_id,day,c.tenant.id,th,claim])]);if(!result[1].meta.changes)throw new DomainError('کد ورود دیگر معتبر نیست.');await audit(c,'attendance.qr',id).run();return {id,name:m.name};}
