import {z} from 'zod';
import {database,rows,one,stmt,insert,uid} from './db';
import {type Context,permit,member,scoped,audit} from './service';
import {DomainError,today} from './domain';
const schema=z.object({name:z.string().trim().min(1).max(120),branch_id:z.string().min(1),trainer_id:z.string().optional().default(''),room:z.string().trim().min(1).max(80),starts_at:z.string().datetime({offset:true}),duration:z.coerce.number().int().min(15).max(480),capacity:z.coerce.number().int().min(1).max(200),notes:z.string().trim().max(1000).default('')});
function manager(c:Context){if(!['owner','manager','staff'].includes(c.access.role))throw new DomainError('مدیر یا پذیرش می‌تواند برنامه کلاس را مدیریت کند.',403)}
function where(c:Context){permit(c,'classes');let filter='s.tenant_id=?',args:any[]=[c.tenant.id];if(c.access.branch_id){filter+=' AND s.branch_id=?';args.push(c.access.branch_id)}if(c.access.role==='trainer'){filter+=' AND s.trainer_id=?';args.push(c.access.id)}if(c.access.role==='member'){filter+=' AND s.branch_id=(SELECT branch_id FROM members WHERE tenant_id=? AND id=?)';args.push(c.tenant.id,c.access.member_id||'')}return {filter,args}}
async function session(c:Context,id:string){const q=where(c);const s=await one(`SELECT s.* FROM class_sessions s WHERE ${q.filter} AND s.id=?`,[...q.args,id]);if(!s)throw new DomainError('کلاس پیدا نشد یا دسترسی ندارید.',404);return s}
function future(s:any){if(s.status!=='SCHEDULED'||Date.parse(s.starts_at)<=Date.now())throw new DomainError('رزرو یا لغو فقط پیش از شروع کلاس فعال مجاز است.',409)}
export async function createClass(c:Context,body:any){manager(c);const parsed=schema.safeParse(body);if(!parsed.success)throw new DomainError('اطلاعات کلاس معتبر نیست؛ نام، شعبه، زمان و ظرفیت را بررسی کنید.');const v=parsed.data;await scoped(c,'branches',v.branch_id);if(c.access.branch_id&&c.access.branch_id!==v.branch_id)throw new DomainError('شعبه مجاز نیست.',403);if(v.trainer_id){const t=await scoped(c,'access',v.trainer_id);if(t.role!=='trainer'||(t.branch_id&&t.branch_id!==v.branch_id))throw new DomainError('مربی این شعبه معتبر نیست.')}
 const start=new Date(v.starts_at),end=new Date(start.getTime()+v.duration*60000);if(start.getTime()<=Date.now()||start.getTime()>Date.now()+366*86400000)throw new DomainError('شروع کلاس باید در آینده و حداکثر یک سال بعد باشد.');const id=uid();await database().batch([insert('class_sessions',{id,tenant_id:c.tenant.id,branch_id:v.branch_id,trainer_id:v.trainer_id||null,name:v.name,room:v.room,starts_at:start.toISOString(),ends_at:end.toISOString(),capacity:v.capacity,notes:v.notes,status:'SCHEDULED'}),audit(c,'classes.created',id)]);return {id};}
export async function listClasses(c:Context,o:Record<string,string>={}){let {filter,args}=where(c);const from=o.from||today();if(!Number.isFinite(Date.parse(from)))throw new DomainError('تاریخ معتبر نیست.');const to=o.to||new Date(Date.parse(from)+30*86400000).toISOString().slice(0,10);const valid=(d:string)=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;if(!valid(from)||!valid(to)||to<from||Date.parse(to)-Date.parse(from)>366*86400000)throw new DomainError('بازه تاریخ کلاس معتبر نیست.');filter+=" AND date(s.starts_at,'+3 hours','+30 minutes') BETWEEN ? AND ?";args.push(from,to);if(o.branch&&o.branch!=='all'){filter+=' AND s.branch_id=?';args.push(o.branch)}if(o.q){filter+=" AND s.name LIKE ? ESCAPE '!'";args.push('%'+o.q.slice(0,120).replace(/[!%_]/g,'!$&')+'%')}
 const total=(await one(`SELECT COUNT(*) n FROM class_sessions s WHERE ${filter}`,args)).n;
 if(o.cursor){let value;try{value=JSON.parse(atob(o.cursor));if(!Array.isArray(value)||value.length!==2||value.some(v=>typeof v!=='string'||v.length>100))throw Error()}catch{throw new DomainError('نشانگر صفحه معتبر نیست.')};filter+=' AND (s.starts_at>? OR (s.starts_at=? AND s.id>?))';args.push(value[0],value[0],value[1])}
 const limit=50,items=await rows(`SELECT s.*,(SELECT name FROM branches b WHERE b.tenant_id=s.tenant_id AND b.id=s.branch_id) branch_name,(SELECT name FROM access a WHERE a.tenant_id=s.tenant_id AND a.id=s.trainer_id) trainer_name,(SELECT COUNT(*) FROM class_bookings b WHERE b.tenant_id=s.tenant_id AND b.session_id=s.id AND b.status IN ('BOOKED','ATTENDED','NO_SHOW')) booked,(SELECT COUNT(*) FROM class_bookings b WHERE b.tenant_id=s.tenant_id AND b.session_id=s.id AND b.status='WAITLIST') waiting,(SELECT status FROM class_bookings b WHERE b.tenant_id=s.tenant_id AND b.session_id=s.id AND b.member_id=?) my_status,(SELECT id FROM class_bookings b WHERE b.tenant_id=s.tenant_id AND b.session_id=s.id AND b.member_id=?) my_booking_id FROM class_sessions s WHERE ${filter} ORDER BY s.starts_at,s.id LIMIT ?`,[c.access.role==='member'?c.access.member_id:null,c.access.role==='member'?c.access.member_id:null,...args,limit+1]);const more=items.length>limit;items.splice(limit);const last=items.at(-1);return {items,total,nextCursor:more?btoa(JSON.stringify([last.starts_at,last.id])):null,from,to};}
export async function bookClass(c:Context,id:string,body:any){if(c.access.role!=='member')manager(c);const s=await session(c,id);future(s);const mid=c.access.role==='member'?c.access.member_id:String(body.member_id||'');const m=await member(c,mid);if(m.branch_id!==s.branch_id)throw new DomainError('عضو باید متعلق به شعبه کلاس باشد.');const existing=await one('SELECT id,status FROM class_bookings WHERE tenant_id=? AND session_id=? AND member_id=?',[c.tenant.id,id,mid]);if(existing&&existing.status!=='CANCELLED')return existing;
 const bid=existing?.id||uid();const statusSQL="CASE WHEN (SELECT COUNT(*) FROM class_bookings b WHERE b.tenant_id=? AND b.session_id=? AND b.status IN ('BOOKED','ATTENDED','NO_SHOW')) < (SELECT capacity FROM class_sessions WHERE tenant_id=? AND id=?) THEN 'BOOKED' ELSE 'WAITLIST' END";const args=[c.tenant.id,id,c.tenant.id,id];const operation=existing?stmt(`UPDATE class_bookings SET status=${statusSQL},queued_at=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND status='CANCELLED'`,[...args,new Date().toISOString(),c.tenant.id,bid]):stmt(`INSERT INTO class_bookings(id,tenant_id,session_id,member_id,status,queued_at) VALUES(?,?,?,?,${statusSQL},?)`,[bid,c.tenant.id,id,mid,...args,new Date().toISOString()]);await database().batch([operation,audit(c,'class_bookings.reserved',bid)]);return one('SELECT id,status FROM class_bookings WHERE tenant_id=? AND id=?',[c.tenant.id,bid]);}
export async function classRoster(c:Context,id:string,o:Record<string,string>={}){const s=await session(c,id);if(c.access.role==='member')throw new DomainError('فهرست دیگر اعضا برای شما قابل مشاهده نیست.',403);let offset=Number(o.offset||0);if(!Number.isSafeInteger(offset)||offset<0)throw new DomainError('صفحه معتبر نیست.');const items=await rows("SELECT b.id,b.member_id,b.status,b.queued_at,m.name,m.phone FROM class_bookings b JOIN members m ON m.tenant_id=b.tenant_id AND m.id=b.member_id WHERE b.tenant_id=? AND b.session_id=? ORDER BY b.queued_at,b.rowid LIMIT 50 OFFSET ?",[c.tenant.id,id,offset]);const total=(await one('SELECT COUNT(*) n FROM class_bookings WHERE tenant_id=? AND session_id=?',[c.tenant.id,id])).n;return {session:s,items,total,nextOffset:offset+items.length<total?offset+items.length:null};}
export async function cancelBooking(c:Context,id:string){const b=await scoped(c,'class_bookings',id);const s=await session(c,b.session_id);future(s);if(c.access.role==='member'){if(b.member_id!==c.access.member_id)throw new DomainError('این رزرو متعلق به شما نیست.',403)}else manager(c);if(b.status==='CANCELLED')return {id};if(b.status!=='BOOKED'&&b.status!=='WAITLIST')throw new DomainError('این رزرو قابل لغو نیست.',409);await database().batch([stmt("UPDATE class_bookings SET status='CANCELLED',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND status IN ('BOOKED','WAITLIST')",[c.tenant.id,id]),audit(c,'class_bookings.cancelled',id)]);return {id};}
export async function cancelClass(c:Context,id:string){manager(c);const s=await session(c,id);if(s.status==='CANCELLED')return {id};future(s);await database().batch([stmt("UPDATE class_sessions SET status='CANCELLED',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=?",[c.tenant.id,id]),audit(c,'classes.cancelled',id)]);return {id};}
export async function markClassAttendance(c:Context,id:string,body:any){if(c.access.role!=='trainer')manager(c);const b=await scoped(c,'class_bookings',id),s=await session(c,b.session_id);if(s.status!=='SCHEDULED'||Date.parse(s.starts_at)>Date.now())throw new DomainError('ثبت حضور پس از شروع کلاس فعال مجاز است.',409);if(!['ATTENDED','NO_SHOW'].includes(body.status))throw new DomainError('وضعیت حضور معتبر نیست.');if(body.status==='NO_SHOW'&&Date.parse(s.ends_at)>Date.now())throw new DomainError('غیبت را پس از پایان کلاس ثبت کنید.',409);if(!['BOOKED','ATTENDED','NO_SHOW'].includes(b.status))throw new DomainError('فقط رزرو تأییدشده قابل حضورگیری است.',409);await database().batch([stmt('UPDATE class_bookings SET status=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND status IN (\'BOOKED\',\'ATTENDED\',\'NO_SHOW\')',[body.status,c.tenant.id,id]),audit(c,'class_bookings.'+body.status,id)]);return {id};}
export async function classOptions(c:Context){manager(c);const args=c.access.branch_id?[c.tenant.id,c.access.branch_id]:[c.tenant.id];return {branches:await rows(`SELECT id,name FROM branches WHERE tenant_id=? ${c.access.branch_id?'AND id=?':''} ORDER BY name`,args),trainers:await rows(`SELECT id,name,branch_id FROM access WHERE tenant_id=? AND role='trainer' ${c.access.branch_id?'AND (branch_id=? OR branch_id IS NULL)':''} ORDER BY name`,args)};}
export async function classCalendar(c:Context,id:string){const s=await session(c,id);const escape=(v:string)=>String(v||'').replace(/\\/g,'\\\\').replace(/\r\n|\r|\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const stamp=(v:string)=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const fold=(line:string)=>{let part='',bytes=0,result='';for(const char of line){const width=new TextEncoder().encode(char).length;if(bytes+width>75){result+=part+'\r\n';part=' ';bytes=1}part+=char;bytes+=width}return result+part};const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//FitSpace//Group Classes//FA','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:'+s.id+'@fitspace','DTSTAMP:'+stamp(new Date().toISOString()),'DTSTART:'+stamp(s.starts_at),'DTEND:'+stamp(s.ends_at),'SUMMARY:'+escape(s.name),'LOCATION:'+escape(s.room),'DESCRIPTION:'+escape(s.notes),'STATUS:'+(s.status==='CANCELLED'?'CANCELLED':'CONFIRMED'),'END:VEVENT','END:VCALENDAR'];return {filename:'fitspace-class-'+s.id+'.ics',content:lines.map(fold).join('\r\n')+'\r\n'};}
