import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {authStore} from '../standalone/auth.mjs';
import {storage} from '../standalone/storage.mjs';
import {start} from '../standalone/server.mjs';
import {backup,restore} from '../standalone/backup.mjs';
const root=resolve('.'),temp=mkdtempSync(resolve(tmpdir(),'fitspace-test-')),dir=resolve(temp,'data');
let runtime,owner;
test('Native login, real app routes, isolation, CSRF, scheduler and session revocation',async()=>{
 const accounts=authStore(dir);owner=await accounts.create({email:'owner@example.com',name:'Owner',password:'testing-password-123',isOwner:true});await assert.rejects(()=>accounts.create({email:'second@example.com',name:'Second',password:'testing-password-123',isOwner:true}),/UNIQUE/);accounts.close();
 const initial=storage(root,dir);initial.db.prepare("INSERT INTO platform_admins(id,user_id,email) VALUES('installation-owner',?,?)").run(owner.id,owner.email);initial.close();
 runtime=await start({root,dataDir:dir,port:0,origin:'http://localhost:3000',schedule:false});const origin='http://localhost:3000',url='http://127.0.0.1:'+runtime.server.address().port;
 const request=(path,options={})=>fetch(url+path,{redirect:'manual',...options});
 assert.equal((await request('/healthz')).status,200);
 assert.equal((await request('/api/gym/bootstrap',{headers:{'oai-authenticated-user-id':owner.id,'oai-authenticated-user-email':owner.email}})).status,401);
 const form=await request('/login');const loginCookie=form.headers.get('set-cookie').split(';')[0],csrf=(await form.text()).match(/name="csrf" value="([^"]+)"/)[1];
 const login=await request('/auth/login',{method:'POST',headers:{origin,cookie:loginCookie,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({email:owner.email,password:'testing-password-123',csrf})});assert.equal(login.status,303);const cookie=login.headers.get('set-cookie').split(';')[0];
 const api=async(path,method='GET',data,extra={})=>request('/api/gym/'+path,{method,headers:{origin,cookie,'Content-Type':'application/json',...extra},body:data?JSON.stringify(data):undefined});
 const home=await request('/',{headers:{cookie}});assert.equal(home.status,200);assert.match(await home.text(),/FitSpace|باشگاه/);
 const boot=await api('bootstrap');assert.equal(boot.status,200);assert.equal((await boot.json()).user.mode,'standalone');
 assert.equal((await api('tenants','POST',{name:'CSRF'},{origin:'https://evil.example'})).status,403);
 const tenantResponse=await api('tenants','POST',{name:'Test Gym'});assert.equal(tenantResponse.status,201);const tenant=(await tenantResponse.json()).id;
 const state=await (await api('state?tenant='+tenant)).json();assert.equal(state.summary.members,0);assert.equal(state.currentAccess.role,'owner');
 const created=await api('members?tenant='+tenant,'POST',{name:'Real Member',phone:'123456789',branch_id:state.branches[0].id});assert.equal(created.status,201);
 const search=await (await api('page/members?tenant='+tenant+'&q=Real')).json();assert.equal(search.total,1);assert.equal(search.items[0].name,'Real Member');
 assert.equal((await api('state?tenant=missing')).status,403);
 const report=await (await api('report?tenant='+tenant)).json();assert.equal(report.summary.members,1);
 await runtime.runScheduled();
 const asset=await request('/standalone/auth.mjs',{headers:{cookie}});assert.notEqual(asset.headers.get('content-type'),'text/javascript');
 const account=await request('/account',{headers:{cookie}});const accountCsrf=(await account.text()).match(/name="csrf" value="([^"]+)"/)[1];
 const changed=await request('/auth/password',{method:'POST',headers:{origin,cookie,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({csrf:accountCsrf,old:'testing-password-123',password:'replacement-password-123'})});assert.equal(changed.status,303);assert.equal((await api('bootstrap')).status,401);
 assert.throws(()=>backup(dir,resolve(temp,'running-backup')),/Stop the server/);
 await runtime.close();runtime=null;
});
test('Backup and restore preserve SQL and objects, reject tampering and clear sessions',async()=>{
 const s=storage(root,dir);await s.BUCKET.put('tenant/member/image',Buffer.from('image-bytes'),{httpMetadata:{contentType:'image/png'}});s.close();
 const a=authStore(dir);const session=await a.login(owner.email,'replacement-password-123','127.0.0.1');assert.ok(a.session(session));a.close();
 const folder=resolve(temp,'backup'),restored=resolve(temp,'restored');backup(dir,folder);restore(folder,restored);
 const data=storage(root,restored);assert.equal(data.db.prepare('SELECT COUNT(*) n FROM members').get().n,1);assert.equal(await new Response((await data.BUCKET.get('tenant/member/image')).body).text(),'image-bytes');data.close();
 const auth=authStore(restored);assert.equal(auth.session(session),undefined);auth.close();
 writeFileSync(resolve(folder,'data/objects/tenant/member/image'),'tampered');assert.throws(()=>restore(folder,resolve(temp,'tampered')),/checksum/);assert.equal(existsSync(resolve(temp,'tampered')),false);
});
test.after(async()=>{if(runtime)await runtime.close();rmSync(temp,{recursive:true,force:true})});
