import {resolve,relative,dirname,sep} from 'node:path';
import {existsSync,readdirSync,readFileSync,writeFileSync,mkdirSync,copyFileSync,lstatSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {pathToFileURL} from 'node:url';
const digest=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
function stopped(dir){const pid=resolve(dir,'server.pid');if(existsSync(pid))throw Error('Stop the server first. If it crashed, verify no instance is running before removing server.pid.');}
function files(dir,prefix=''){return readdirSync(dir).flatMap(name=>{const path=resolve(dir,name),s=lstatSync(path),key=prefix+name;if(s.isSymbolicLink())throw Error('Symbolic links are not supported in backups');return s.isDirectory()?files(path,key+'/'):s.isFile()?[key]:[]})}
export function backup(source,dest){source=resolve(source);dest=resolve(dest);stopped(source);if(dest===source||dest.startsWith(source+sep))throw Error('Backup must be outside the data directory');if(existsSync(dest))throw Error('Destination must not exist');for(const name of ['fitspace.sqlite','accounts.sqlite']){if(!existsSync(resolve(source,name)))throw Error('Incomplete data directory');const db=new DatabaseSync(resolve(source,name));db.exec('PRAGMA wal_checkpoint(TRUNCATE)');db.close();}const manifest={version:1,createdAt:new Date().toISOString(),files:files(source).filter(f=>!f.endsWith('-wal')&&!f.endsWith('-shm')).map(path=>({path,sha256:digest(resolve(source,path))}))};mkdirSync(dest,{recursive:true,mode:0o700});for(const f of manifest.files){const target=resolve(dest,'data',f.path);mkdirSync(dirname(target),{recursive:true});copyFileSync(resolve(source,f.path),target)}writeFileSync(resolve(dest,'manifest.json'),JSON.stringify(manifest,null,2));return manifest;}
export function restore(source,dest){source=resolve(source);dest=resolve(dest);if(existsSync(dest))throw Error('Restore destination must not exist');const m=JSON.parse(readFileSync(resolve(source,'manifest.json'),'utf8'));if(m.version!==1||!Array.isArray(m.files))throw Error('Unsupported backup');for(const f of m.files){if(typeof f.path!=='string'||f.path.includes('\\')||f.path.startsWith('/')||f.path.split('/').some(p=>!p||p==='.'||p==='..')||f.path==='server.pid')throw Error('Invalid backup path');const path=resolve(source,'data',f.path);let part=resolve(source,'data');for(const component of f.path.split('/')){part=resolve(part,component);if(lstatSync(part).isSymbolicLink())throw Error('Symbolic link in backup')}if(digest(path)!==f.sha256)throw Error('Backup checksum mismatch: '+f.path)}if(!['fitspace.sqlite','accounts.sqlite'].every(n=>m.files.some(f=>f.path===n)))throw Error('Incomplete backup');mkdirSync(dest,{recursive:true,mode:0o700});for(const f of m.files){const target=resolve(dest,f.path);mkdirSync(dirname(target),{recursive:true});copyFileSync(resolve(source,'data',f.path),target)}const auth=new DatabaseSync(resolve(dest,'accounts.sqlite'));auth.exec('DELETE FROM sessions');auth.close();return m;}
if(process.argv[1]&&pathToFileURL(resolve(process.argv[1])).href===import.meta.url){try{const data=resolve(process.env.FITSPACE_DATA_DIR||'data');if(process.argv[2]==='restore'){if(!process.argv[3])throw Error('Pass the backup directory');restore(process.argv[3],data);console.log('Restored to '+data+'; previous sessions revoked.')}else{const dest=resolve(process.argv[2]||'backups/'+new Date().toISOString().replace(/[:.]/g,'-'));backup(data,dest);console.log('Backup saved to '+dest)}}catch(e){console.error(e.message);process.exitCode=1}}
