import {createServer} from 'node:http';
import {resolve,extname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {existsSync,readFileSync,writeFileSync,rmSync,statSync} from 'node:fs';
import {Readable} from 'node:stream';
import {authStore,token} from './auth.mjs';
import {storage} from './storage.mjs';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=(title,body,status=200)=>new Response(`<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · FitSpace</title><style>body{font-family:Tahoma,sans-serif;max-width:480px;margin:8vh auto;padding:24px;background:#151a17;color:#eee}h1{color:#c9f269}label{display:block;margin:18px 0}input{display:block;width:90%;padding:12px;border:1px solid #555;border-radius:8px;margin-top:8px}button,a{display:inline-block;padding:12px;color:#c9f269}button{background:#c9f269;color:#16200a;border:0;border-radius:8px;cursor:pointer}</style><h1>${escape(title)}</h1>${body}</html>`,{status,headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'}});
const field=(name,label,type='text')=>`<label>${label}<input name="${name}" type="${type}" required ${type==='password'?'maxlength="128" autocomplete="current-password"':''}></label>`;
const redirect=path=>new Response(null,{status:303,headers:{Location:path}});
const cookies=value=>Object.fromEntries(String(value||'').split(';').map(v=>v.trim().split(/=(.*)/s).slice(0,2)));
async function body(req,max){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>max)throw Object.assign(Error('حجم درخواست بیش از حد است.'),{status:413});chunks.push(c)}return Buffer.concat(chunks)}
export async function start(options={}){
 const root=resolve(options.root||process.cwd()),dataDir=resolve(options.dataDir||process.env.FITSPACE_DATA_DIR||'data'),origin=new URL(options.origin||process.env.FITSPACE_ORIGIN||'http://localhost:3000').origin,secure=origin.startsWith('https:');
 if(process.env.NODE_ENV==='production'&&!secure)throw Error('Production requires HTTPS FITSPACE_ORIGIN behind a TLS reverse proxy');
 const auth=authStore(dataDir);if(!auth.owner()){auth.close();throw Error('Create the installation owner with npm run account:create -- --email ... --name ... --owner')}
 const pid=resolve(dataDir,'server.pid');if(existsSync(pid)){const old=Number(readFileSync(pid,'utf8'));let alive=false;try{process.kill(old,0);alive=true}catch(e){if(e.code!=='ESRCH')alive=true}if(alive){auth.close();throw Error('Another server is using this data directory')}rmSync(pid)}
 writeFileSync(pid,String(process.pid),{flag:'wx',mode:0o600});let store;try{store=storage(root,dataDir)}catch(e){auth.close();rmSync(pid,{force:true});throw e}globalThis[Symbol.for('fitspace.runtime')]={DB:store.DB,BUCKET:store.BUCKET};
 let handler;try{handler=(await import(pathToFileURL(resolve(root,'dist-standalone/server/index.js')).href)).default}catch(e){store.close();auth.close();rmSync(pid,{force:true});throw e}
 const tasks=new Set();const ctx={waitUntil:p=>{tasks.add(p);p.then(()=>tasks.delete(p),e=>{tasks.delete(p);console.error('Background task failed',e.message)})}};
 const app=req=>typeof handler==='function'?handler(req,ctx):handler.fetch(req,globalThis[Symbol.for('fitspace.runtime')],ctx);
 const cookieName=secure?'__Host-fitspace':'fitspace';const cookie=(name,value,age=43200)=>`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${secure?'; Secure':''}`;
 const trustedHeaders=(source,user)=>{const h=new Headers();for(const [key,value]of Object.entries(source))if(value&&!/^(oai-|x-fitspace-|host$|cookie$|content-length$)/i.test(key))h.set(key,Array.isArray(value)?value.join(','):value);h.set('x-fitspace-auth-mode','standalone');h.set('oai-authenticated-user-id',user.id);h.set('oai-authenticated-user-email',user.email);h.set('oai-authenticated-user-full-name',encodeURIComponent(user.name));h.set('oai-authenticated-user-full-name-encoding','percent-encoded-utf-8');return h;};
 async function respond(req){const url=new URL(req.url,origin);if(url.origin!==origin)return page('درخواست نامعتبر','',400);const path=decodeURIComponent(url.pathname),jar=cookies(req.headers.cookie),session=auth.session(jar[cookieName]);
  if(path==='/healthz')return Response.json({ok:true,version:'0.3.0'});
  if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==origin)return page('مبدأ درخواست نامعتبر','',403);
  if(['/login','/signin-with-chatgpt'].includes(path)&&req.method==='GET'){const csrf=token();const r=page('ورود به FitSpace',`<form method="post" action="/auth/login"><input type="hidden" name="csrf" value="${csrf}">${field('email','ایمیل','email')}${field('password','رمز عبور','password')}<button>ورود</button></form>`);r.headers.set('Set-Cookie',cookie('fitspace-login',csrf,600));return r;}
  if(path==='/auth/login'&&req.method==='POST'){const f=new URLSearchParams((await body(req,8192)).toString());if(!jar['fitspace-login']||f.get('csrf')!==jar['fitspace-login'])return page('فرم ورود منقضی شده','<a href="/login">تلاش دوباره</a>',403);const t=await auth.login(f.get('email'),f.get('password'),req.socket.remoteAddress||'unknown');if(!t)return page('ایمیل یا رمز اشتباه است','<a href="/login">تلاش دوباره</a>',401);const r=redirect('/');r.headers.set('Set-Cookie',cookie(cookieName,t));return r;}
  if(!session)return path.startsWith('/api/')?Response.json({error:'ورود لازم است.'},{status:401}):redirect('/login');
  const hidden=`<input type="hidden" name="csrf" value="${session.csrf}">`;
  if(path==='/signout-with-chatgpt'&&req.method==='GET')return page('خروج از حساب',`<form method="post" action="/auth/logout">${hidden}<button>خروج</button></form>`);
  if(path==='/account'&&req.method==='GET')return page('مدیریت حساب',`<p>${escape(session.email)}</p><form method="post" action="/auth/password">${hidden}${field('old','رمز فعلی','password')}${field('password','رمز جدید (حداقل ۱۲ نویسه)','password')}<button>تغییر رمز و خروج</button></form>${session.is_owner?'<a href="/accounts">ساخت حساب کاربری</a>':''}<a href="/">بازگشت به باشگاه</a>`);
  if(path==='/accounts'&&req.method==='GET'){if(!session.is_owner)return page('دسترسی ندارید','',403);return page('حساب جدید',`<p>پس از ساخت حساب، ایمیل را در تیم باشگاه با نقش مناسب اضافه کنید.</p><form method="post" action="/auth/create">${hidden}${field('name','نام')}${field('email','ایمیل','email')}${field('password','رمز موقت (حداقل ۱۲ نویسه)','password')}<button>ساخت حساب</button></form><a href="/account">بازگشت</a>`);}
  if(path.startsWith('/auth/')&&req.method==='POST'){const f=new URLSearchParams((await body(req,8192)).toString());if(f.get('csrf')!==session.csrf)return page('فرم نامعتبر','',403);if(path==='/auth/logout'){auth.logout(jar[cookieName]);const r=redirect('/login');r.headers.set('Set-Cookie',cookie(cookieName,'',0));return r;}if(path==='/auth/password'){await auth.change(session.id,f.get('old'),f.get('password'));return redirect('/login')}if(path==='/auth/create'){if(!session.is_owner)return page('دسترسی ندارید','',403);await auth.create({email:f.get('email'),name:f.get('name'),password:f.get('password')});return page('حساب ساخته شد','<p>ایمیل کاربر را با نقش مناسب در تیم باشگاه اضافه کنید. رمز موقت را از مسیر امن به او بدهید؛ کاربر می‌تواند در صفحه حساب آن را تغییر دهد.</p><a href="/accounts">حساب جدید</a><a href="/">باشگاه</a>');}return page('مسیر پیدا نشد','',404);}
  const publicDir=resolve(root,'dist-standalone/client'),file=resolve(publicDir,'.'+path);if(file.startsWith(publicDir+sep)&&!path.split('/').some(v=>v.startsWith('.'))&&existsSync(file)&&statSync(file).isFile()){const types={'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.ico':'image/x-icon'};return new Response(readFileSync(file),{headers:{'Content-Type':types[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'}})}
  const payload=['GET','HEAD'].includes(req.method)?undefined:await body(req,6*1024*1024);return app(new Request(url,{method:req.method,headers:trustedHeaders(req.headers,session),body:payload}));
 }
 const server=createServer(async(req,res)=>{try{const r=await respond(req);r.headers.set('Cache-Control','private, no-store');r.headers.set('X-Content-Type-Options','nosniff');res.writeHead(r.status,Object.fromEntries(r.headers));if(r.body&&req.method!=='HEAD')Readable.fromWeb(r.body).pipe(res);else res.end()}catch(e){const r=page('درخواست انجام نشد',escape(e.status?e.message:'اطلاعات را بررسی کنید و دوباره تلاش کنید.'),e.status||400);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());console.error('Request failed:',e.message)}});
 server.requestTimeout=30000;server.headersTimeout=15000;
 let running=null;const runScheduled=()=>{if(running)return running;running=(async()=>{auth.cleanup();store.db.prepare("DELETE FROM rate_limits WHERE bucket<?").run(Math.floor(Date.now()/60000)-2);store.db.prepare("DELETE FROM qr_tokens WHERE expires_at<?").run(Date.now());const tenants=store.db.prepare("SELECT t.id,a.email FROM tenants t JOIN access a ON a.tenant_id=t.id AND a.role='owner' WHERE t.plan='ENTERPRISE' OR (t.plan='PRO' AND (t.trial_until='' OR t.trial_until>?))").all(new Date().toISOString());for(const t of tenants){const r=await app(new Request(origin+'/api/gym/automations-run?tenant='+encodeURIComponent(t.id),{method:'POST',headers:trustedHeaders({origin,'content-type':'application/json'},{id:'scheduler:'+t.id,email:t.email,name:'Scheduler'}),body:'{}'}));if(!r.ok)console.error('Scheduled run failed:',r.status,t.id)}})().finally(()=>{running=null});return running};
 try{await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(options.port??Number(process.env.PORT||3000),options.host||'0.0.0.0',resolve)})}catch(e){store.close();auth.close();rmSync(pid,{force:true});throw e}
 const interval=options.schedule===false?null:setInterval(()=>runScheduled().catch(e=>console.error('Scheduler:',e.message)),300000);interval?.unref();
 if(interval)runScheduled().catch(e=>console.error('Scheduler:',e.message));
 return {server,auth,store,runScheduled,origin,close:async()=>{if(interval)clearInterval(interval);await new Promise(r=>server.close(r));if(running)await running.catch(()=>{});await Promise.allSettled([...tasks]);store.close();auth.close();rmSync(pid,{force:true})}};
}
if(process.argv[1]&&pathToFileURL(resolve(process.argv[1])).href===import.meta.url){const runtime=await start();console.log('FitSpace is listening at '+runtime.origin);for(const signal of ['SIGINT','SIGTERM'])process.once(signal,async()=>{await runtime.close();process.exit(0)})}
