'use client';
import {useCallback,useEffect,useState,useMemo,useRef} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import EntityPicker from './entity-picker';
import ReportsView from './reports-view';
import {Pagination,PaginationContent,PaginationItem,PaginationLink} from '@/components/ui/pagination';
import QrDialog from './qr-dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Activity,ArrowUpLeft,Bell,Building2,CalendarCheck,ChartNoAxesCombined,Check,ChevronLeft,CreditCard,Dumbbell,Flame,LayoutDashboard,LogOut,Menu,Moon,Package,Plus,Search,Settings2,ShieldCheck,ShoppingBag,Sun,Target,Trash2,Users,Utensils,Zap,HeartPulse,Download,CheckCircle2,Clock,RefreshCw,FileText,UserRound, X} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarFooter,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Skeleton} from '@/components/ui/skeleton';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,LineChart,Line} from 'recharts';
import {can,daysLeft,today} from '@/lib/gym/domain';
type Row=Record<string,any>;
const number=(v:number|string=0)=>Number(v||0).toLocaleString('fa-IR');
const money=(v:number=0)=>`${number(v)} تومان`;
const date=(v:string)=>{try{return new Date(v).toLocaleDateString('fa-IR',{year:'numeric',month:'short',day:'numeric'})}catch{return v}};
const labels:Row={ACTIVE:'فعال',INACTIVE:'غیرفعال',UPCOMING:'شروع در آینده',EXPIRED:'منقضی',EXPIRING_SOON:'رو به پایان',SUSPENDED:'تعلیق',CANCELLED:'لغوشده',PENDING:'در انتظار پرداخت',PAID:'پرداخت‌شده',PROCESSING:'در حال آماده‌سازی',READY:'آماده تحویل',COMPLETED:'تحویل‌شده',CONFIRMED:'تأییدشده',OPEN:'باز',DONE:'انجام‌شده',revoked:'لغو دسترسی',owner:'مالک باشگاه',manager:'مدیر',trainer:'مربی',staff:'پذیرش',member:'عضو',STARTER:'پایه',PRO:'حرفه‌ای',ENTERPRISE:'سازمانی',MEMBERSHIP:'شهریه',ORDER:'سفارش',PT:'تمرین خصوصی',OTHER:'سایر'};
const nav=[['dashboard','نمای کلی',LayoutDashboard],['members','اعضا',Users],['memberships','عضویت‌ها',CreditCard],['attendance','حضور و غیاب',CalendarCheck],['programs','برنامه تمرینی',Dumbbell],['nutrition','برنامه غذایی',Utensils],['progress','پیشرفت اعضا',Activity],['access','تیم باشگاه',UserRound],['products','فروشگاه',ShoppingBag],['orders','سفارش‌ها',Package],['payments','پرداخت‌ها',CreditCard],['reports','گزارش‌ها',ChartNoAxesCombined],['crm','پیگیری اعضا',HeartPulse],['automations','اتوماسیون',Zap],['notifications','اعلان‌ها',Bell],['settings','تنظیمات',Settings2]] as const;
const navDomain:Row={nutrition:'programs',progress:'measurements',reports:'audit_logs',crm:'crm_tasks'};
function Pick({value,onChange,options,placeholder='انتخاب کنید',required=false}:{value:string,onChange:(v:string)=>void,options:[string,string][],placeholder?:string,required?:boolean}){return <Select dir="rtl" value={value||undefined} onValueChange={onChange} required={required}><SelectTrigger className="picker"><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.filter(o=>o[0]).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select>}
function Status({value}:{value:string}){return <span className={`status status-${value}`}>{labels[value]||value}</span>}
function Blank({title='هنوز موردی ثبت نشده',description='با ثبت اولین مورد، اطلاعات این بخش نمایش داده می‌شود.',action}:{title?:string,description?:string,action?:React.ReactNode}){return <Empty className="empty"><EmptyHeader><div className="empty-icon"><Dumbbell size={24}/></div><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action}</Empty>}
function Button({children,onClick,variant='',disabled=false,type='button'}:{children:React.ReactNode,onClick?:()=>void,variant?:string,disabled?:boolean,type?:'button'|'submit'}){return <button type={type} className={`btn ${variant}`} onClick={onClick} disabled={disabled}>{children}</button>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function DataTable({columns,rows:items,onRow}:{columns:[string,string,((r:Row)=>React.ReactNode)?][],rows:Row[],onRow?:(r:Row)=>void}){if(!items.length)return <Blank/>;return <div className="table-wrap"><Table><TableHeader><TableRow>{columns.map(([key,label])=><TableHead key={key}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{items.map(r=><TableRow key={r.id} onClick={()=>onRow?.(r)} className={onRow?'clickable':''}>{columns.map(([key,,render])=><TableCell key={key}>{render?render(r):r[key]||'—'}</TableCell>)}</TableRow>)}</TableBody></Table></div>}
export default function GymApp({displayName}:{displayName:string}){
 const router=useRouter(),pathname=usePathname();const view=pathname.split('/')[1]||'dashboard';
 const requestEpoch=useRef(0);
 const [boot,setBoot]=useState<Row|null>(null),[tid,setTid]=useState(''),[baseData,setData]=useState<Row|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[dark,setDark]=useState(false),[modal,setModal]=useState<Row|null>(null),[detail,setDetail]=useState<Row|null>(null),[cart,setCart]=useState<Row[]>([]),[platform,setPlatform]=useState<Row[]>([]),[branch,setBranch]=useState('all');
 const api=useCallback(async(path:string,method='GET',body?:any,tenant=tid)=>{const r=await fetch(`/api/gym/${path}${tenant?(path.includes('?')?'&':'?')+'tenant='+encodeURIComponent(tenant):''}`,{method,headers:body instanceof FormData?{}:body?{'Content-Type':'application/json'}:{},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});const j:any=await r.json();if(!r.ok)throw new Error(j.error||'خطا در دریافت اطلاعات');return j;},[tid]);
 const collection=({nutrition:'programs',progress:'measurements',crm:'crm_tasks'} as Row)[view]||view;
 const paged=['members','memberships','attendance','access','products','orders','payments','programs','nutrition','progress','notifications','crm'].includes(view);
 const [listing,setListing]=useState<Row|null>(null),[cursor,setCursor]=useState(''),[history,setHistory]=useState<string[]>([]),[pageBusy,setPageBusy]=useState(false);
 const pageEpoch=useRef(0);
 const data=baseData&&paged&&listing?{...baseData,[collection]:listing.items}:baseData;
 useEffect(()=>{setCursor('');setHistory([]);setListing(null)},[view,query,branch,tid]);
 useEffect(()=>{const epoch=++pageEpoch.current;if(!baseData||!paged||!can(baseData.currentAccess.role,collection))return;setPageBusy(true);const timer=setTimeout(()=>{const params=new URLSearchParams({q:query,branch,cursor,limit:'50'});if(view==='nutrition'||view==='programs')params.set('kind',view==='nutrition'?'nutrition':'workout');api('page/'+collection+'?'+params).then(r=>{if(epoch===pageEpoch.current)setListing(r)}).catch(e=>{if(epoch===pageEpoch.current)toast.error(e.message)}).finally(()=>{if(epoch===pageEpoch.current)setPageBusy(false)})},200);return()=>{clearTimeout(timer);pageEpoch.current++}},[baseData,view,query,branch,tid,cursor,api,collection,paged]);
 const refresh=useCallback(async()=>{if(!tid)return;const epoch=++requestEpoch.current;setLoading(true);setError('');try{const state=await api('state');if(epoch===requestEpoch.current)setData(state);}catch(e){if(epoch===requestEpoch.current)setError((e as Error).message)}finally{if(epoch===requestEpoch.current)setLoading(false)}},[tid,api]);
 useEffect(()=>{api('bootstrap','GET',undefined,'').then(b=>{setBoot(b);if(b.tenants[0])setTid(b.tenants[0].id);else setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)});const preference=localStorage.getItem('fitspace-theme');setDark(preference==='dark');},[]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('fitspace-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{setData(null);setBranch('all');setCart([]);refresh()},[tid]);
 useEffect(()=>{setQuery('');setDetail(null);if(view==='platform'&&boot?.admin)api('platform').then(r=>setPlatform(r.tenants)).catch(e=>toast.error(e.message))},[view,boot?.admin]);
 const go=(v:string)=>router.push(v==='dashboard'?'/':'/'+v);
 const act=async(path:string,method:string,body:any)=>{setBusy(true);try{const r=await api(path,method,body);await refresh();toast.success('با موفقیت ثبت شد');return r;}catch(e){toast.error((e as Error).message);throw e;}finally{setBusy(false)}};
 const createGym=async(name:string)=>{setBusy(true);try{const r=await api('tenants','POST',{name},'');const b=await api('bootstrap','GET',undefined,'');setBoot(b);setTid(r.id);setModal(null);go('dashboard');toast.success('باشگاه شما آماده است.');}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const role=data?.currentAccess?.role||'owner',isMember=role==='member',isTrainer=role==='trainer';
 const members:Row[]=(data?.members||[]).filter((m:Row)=>branch==='all'||m.branch_id===branch);
 const memberName=(id:string)=>data?.members?.find((m:Row)=>m.id===id)?.name||'عضو';
 const branchName=(id:string)=>data?.branches?.find((b:Row)=>b.id===id)?.name||'شعبه';
 const trainerName=(id:string)=>data?.access?.find?.((a:Row)=>a.id===id)?.name||'';
 const team:Row[]=Array.isArray(data?.access)?data!.access:[];
 const filtered=(rs:Row[])=>paged?rs:rs.filter(r=>!query||[r.name,r.phone,r.email,r.reference,memberName(r.member_id)].some(v=>String(v||'').includes(query)));
 const visible=(rs:Row[])=>paged||branch==='all'?rs:rs.filter(r=>members.some(m=>m.id===r.member_id));
 const open=(type:string,record?:Row)=>setModal({type,record});
 const nextStatus:Row={PAID:'PROCESSING',PROCESSING:'READY',READY:'COMPLETED'};
 const getBalance=(r:Row,kind:string)=>r.balance??((r.price??r.total)-((data?.payments||[]).filter((p:Row)=>p[kind]===r.id).reduce((s:number,p:Row)=>s+p.amount,0)));
 const selectedMember=data?.members?.find((m:Row)=>m.id===data?.currentAccess?.member_id)||members[0];
 const ownMembership=(data?.memberships||[]).find((m:Row)=>['ACTIVE','EXPIRING_SOON'].includes(m.status));
 const download=(rs:Row[],name:string)=>{if(!rs.length){toast.error('اطلاعاتی برای خروجی وجود ندارد.');return}const keys=Object.keys(rs[0]);const esc=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const csv='\uFEFF'+[keys.map(esc).join(','),...rs.map(r=>keys.map(k=>esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();URL.revokeObjectURL(url)};
 if(!boot&&loading)return <div className="initial-loading"><div className="brand"><Dumbbell/> FitSpace</div><Skeleton className="h-12 w-64"/><p>در حال آماده‌سازی فضای شما…</p></div>;
 if(!boot)return <div className="initial-loading"><p role="alert">{error}</p><Button onClick={()=>location.reload()}>تلاش دوباره</Button></div>;
 if(!boot.tenants.length)return <><Toaster position="top-center"/><div className="onboarding"><div className="onboard-art"><div className="brand"><span className="brand-icon"><Dumbbell/></span> FitSpace<span className="brand-dot">.</span></div><div><div className="eyebrow">YOUR CLUB. CONNECTED.</div><h1>باشگاهت را<br/>یک قدم جلو ببر.</h1><p>از اولین ورود تا رکورد بعدی؛<br/>همه چیز در یک فضای منظم.</p><div className="onboard-features"><span><Users/>اعضا و عضویت‌ها</span><span><Dumbbell/>تمرین و تغذیه</span><span><ChartNoAxesCombined/>فروش و عملکرد</span></div></div><span className="onboard-foot">فضای کار اختصاصی باشگاه شما</span></div><div className="onboard-form"><span className="small-tag">راه‌اندازی باشگاه</span><h2>به فیت‌اسپیس خوش آمدید</h2><p className="muted">نام باشگاه را وارد کنید. بعد از ورود می‌توانید پلن‌ها، تیم و اعضای خود را اضافه کنید.</p><form onSubmit={e=>{e.preventDefault();createGym(String(new FormData(e.currentTarget).get('name')))}}><Field label="نام باشگاه"><input name="name" placeholder="مثلاً باشگاه ورزشی اوج" required maxLength={120}/></Field><Button type="submit" disabled={busy}>{busy?'در حال ایجاد…':'ایجاد فضای باشگاه'}<ArrowUpLeft size={18}/></Button></form><div className="onboard-note"><ShieldCheck/><span>اطلاعات هر باشگاه مستقل است.<br/>۱۴ روز دسترسی آزمایشی به امکانات حرفه‌ای.</span></div><div className="account-note" dir="ltr">{boot.user.email}</div></div></div></>;
 const access=data?.currentAccess||{}, currentRole=access.role||'owner';
 const allowedNav=nav.filter(([key])=>can(currentRole,navDomain[key]||key)&&(!['products','orders'].includes(key)||data?.tenant?.entitlements?.store));
 const heading=nav.find(n=>n[0]===view)?.[1]||(view==='platform'?'مدیریت سامانه':'نمای کلی');
 const isAllowed=view==='platform'?boot.admin:can(currentRole,navDomain[view]||view);
 const activeMemberships=visible(data?.memberships||[]).filter(m=>['ACTIVE','EXPIRING_SOON'].includes(m.status));
 const expiring=activeMemberships.filter(m=>m.status==='EXPIRING_SOON');
 const attendance=visible(data?.attendance||[]);
 const payments=visible(data?.payments||[]);
 const chart=(data?.reporting?.daily||[]).map((r:Row)=>({day:new Date(r.date).toLocaleDateString('fa-IR',{day:'numeric',month:'short'}),visits:r.attendance,revenue:r.revenue}));
 const financeAllowed=can(currentRole,'payments');
 const write=(domain:string)=>can(currentRole,domain,true);
 const addButtons:Row={members:['members','عضو جدید'],memberships:['memberships','ثبت عضویت'],attendance:['attendance','ثبت ورود'],programs:['programs','برنامه جدید'],nutrition:['nutrition','برنامه غذایی'],progress:['measurements','ثبت اندازه‌گیری'],access:['access','افزودن همکار'],products:['products','محصول جدید'],payments:['payments','ثبت پرداخت'],notifications:['notifications','اعلان جدید']};
 const add=addButtons[view];
 return <SidebarProvider><Toaster richColors position="top-center"/><Sidebar side="right" className="gym-sidebar"><SidebarHeader><div className="brand"><span className="brand-icon"><Dumbbell size={22}/></span>FitSpace<span className="brand-dot">.</span></div><div className="tenant-picker"><Building2 size={18}/><Pick value={tid} onChange={setTid} options={boot.tenants.map((t:Row)=>[t.id,t.name])}/></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>فضای باشگاه</SidebarGroupLabel><SidebarMenu>{allowedNav.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={view===key} size="lg" onClick={()=>go(key)}><Icon size={19}/><span>{currentRole==='member'&&key==='progress'?'پیشرفت من':currentRole==='member'&&key==='members'?'پرونده من':label}</span>{key==='notifications'&&data?.notifications?.filter((n:Row)=>!n.read_at).length>0&&<b className="nav-count">{number(data!.notifications.filter((n:Row)=>!n.read_at).length)}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>{boot.admin&&<SidebarGroup><SidebarGroupLabel>مدیریت پلتفرم</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton onClick={()=>go('platform')} isActive={view==='platform'}><ShieldCheck/><span>باشگاه‌ها و اشتراک‌ها</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup>}</SidebarContent><SidebarFooter><div className="sidebar-plan"><div><Zap size={17}/><b>پلن {labels[data?.tenant?.entitlements?.plan||'PRO']}</b></div><span>{data?.tenant?.trial_until?`دوره آزمایشی تا ${date(data.tenant.trial_until)}`:'اشتراک فعال باشگاه'}</span></div><div className="sidebar-user"><div className="avatar">{displayName.slice(0,1).toUpperCase()}</div><div><b>{displayName.includes('@')?displayName.split('@')[0]:displayName}</b><span>{labels[currentRole]}</span>{boot.user.mode==='standalone'&&<a href="/account" className="text-btn">حساب من</a>}</div><a aria-label="خروج از حساب" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut size={18}/></a></div></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>فضای کار</span><ChevronLeft size={14}/><strong>{heading}</strong></div><div className="top-actions"><span className="today">{new Date().toLocaleDateString('fa-IR',{weekday:'long',day:'numeric',month:'long'})}</span><button className="icon-btn" aria-label="تغییر حالت روشن و تاریک" onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="icon-btn bell" aria-label="اعلان‌ها" onClick={()=>go('notifications')}><Bell size={19}/>{data?.notifications?.some((n:Row)=>!n.read_at)&&<i/>}</button><div className="avatar small">{displayName.slice(0,1).toUpperCase()}</div></div></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow">{view==='dashboard'?'CLUB OVERVIEW':'FITSPACE / '+view.toUpperCase()}</div><h1>{view==='dashboard'?currentRole==='member'?'وقت یک قدم جلوتر رفتن است':`نبض باشگاه ${data?.tenant?.name||''}`:heading}</h1><p>{view==='dashboard'?'هر چیزی که برای شروع امروز نیاز دارید.':({members:'هر عضو، یک مسیر تازه. همه اطلاعات در یک نگاه.',memberships:'اعتبار، تمدید و روزهای باقی‌مانده اعضا.',attendance:'ورودهای امروز و سابقه فعالیت اعضا.',programs:'تمرین هدفمند، متناسب با مسیر هر عضو.',nutrition:'وعده‌ها و مواد مغذی، در یک برنامه مشخص.',products:'محصولات، سفارش‌ها و موجودی باشگاه.',payments:'شهریه و فروش؛ رسیدهای ثبت‌شده در پذیرش.',reports:'تصویری روشن از فعالیت و درآمد باشگاه.',access:'دسترسی مناسب برای هر همکار.',progress:'تغییرات کوچک را به پیشرفت قابل اندازه‌گیری تبدیل کنید.'} as Row)[view]||'اطلاعات به‌روز و قابل پیگیری باشگاه.'}</p></div><div className="heading-actions">{data?.branches?.length>1&&<Pick value={branch} onChange={setBranch} options={[["all","همه شعبه‌ها"],...data!.branches.map((b:Row)=>[b.id,b.name]) as [string,string][]]}/>}<button className="icon-btn" aria-label="تازه‌سازی" onClick={refresh} disabled={loading}><RefreshCw size={18} className={loading?'spin':''}/></button>{add&&write(navDomain[view]||view)&&<Button onClick={()=>open(add[0])}><Plus size={18}/>{add[1]}</Button>}{view==='dashboard'&&write('members')&&<Button onClick={()=>open('members')}><Plus size={18}/>عضو جدید</Button>}</div></div>
 {error&&<div className="error-banner" role="alert">{error}<Button variant="secondary" onClick={refresh}>تلاش دوباره</Button></div>}
 {!data?<div className="stats-grid">{[1,2,3,4].map(i=><Skeleton key={i} className="h-36 rounded-2xl"/>)}</div>:!isAllowed?<Blank title="دسترسی به این بخش ندارید" description="برای تغییر دسترسی با مالک باشگاه تماس بگیرید."/>:<>
 {view==='dashboard'&&<>
 {currentRole==='member'?<><div className="member-welcome"><div><span className="small-tag">عضویت من</span><h2>{ownMembership?number(Math.max(0,daysLeft(ownMembership.end_date)))+' روز باقی‌مانده':'عضویت فعالی ندارید'}</h2><p>{ownMembership?'اعتبار تا '+date(ownMembership.end_date):'برای ثبت یا تمدید عضویت با پذیرش باشگاه تماس بگیرید.'}</p>{ownMembership&&<Progress value={Math.max(0,100*(daysLeft(ownMembership.end_date)+1)/(daysLeft(ownMembership.end_date,ownMembership.start_date)+1))}/>}</div><div className="membership-symbol"><Dumbbell size={68}/></div></div><div className="stats-grid three"><Metric label="حضور این ماه" value={number(attendance.filter(a=>a.day.slice(0,7)===today().slice(0,7)).length)} suffix="جلسه" Icon={CalendarCheck}/><Metric label="آخرین وزن ثبت‌شده" value={number(data.measurements[0]?.weight||0)} suffix="کیلوگرم" Icon={Activity}/><Metric label="برنامه‌های اختصاصی" value={number(data.programs.length)} suffix="برنامه" Icon={Dumbbell}/></div></>:<div className="stats-grid"><Metric label="اعضای فعال" value={number(branch==='all'?data.summary.active:new Set(activeMemberships.map(m=>m.member_id)).size)} suffix="عضو" Icon={Users} accent/><Metric label="ورودهای امروز" value={number(branch==='all'?data.summary.attendance:attendance.filter(a=>a.day===today()).length)} suffix="ورود" Icon={CalendarCheck}/><Metric label={financeAllowed?'درآمد این ماه':'اعضای اختصاص‌یافته'} value={number(financeAllowed?(branch==='all'?data.summary.revenue:payments.filter(p=>p.date.slice(0,7)===today().slice(0,7)).reduce((s,p)=>s+p.amount,0)):members.length)} suffix={financeAllowed?'تومان':'عضو'} Icon={financeAllowed?CreditCard:UserRound}/><Metric label="عضویت رو به پایان" value={number(expiring.length)} suffix="۷ روز آینده" Icon={Clock} warning/></div>}
 <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>ریتم حضور اعضا</h2><p>ورودهای ثبت‌شده در ۱۴ روز گذشته</p></div><span className="chart-key"><i/>تعداد ورود</span></div>{attendance.length?<div className="chart"><ResponsiveContainer width="100%" height={240}><AreaChart data={chart}><defs><linearGradient id="visits" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a5d849" stopOpacity={.35}/><stop offset="100%" stopColor="#a5d849" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="var(--border)"/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={12} minTickGap={25}/><YAxis allowDecimals={false} tickLine={false} axisLine={false} width={28} fontSize={12}/><Tooltip contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:12}}/><Area type="monotone" name="ورود" dataKey="visits" stroke="#80b12b" strokeWidth={3} fill="url(#visits)"/></AreaChart></ResponsiveContainer></div>:<div className="chart-empty"><ChartNoAxesCombined size={36}/><b>ریتم باشگاه از اولین ورود شروع می‌شود</b><span>پس از ثبت حضور اعضا، نمودار اینجا شکل می‌گیرد.</span>{write('attendance')&&<Button variant="secondary" onClick={()=>open('attendance')}>ثبت اولین ورود<ArrowUpLeft size={16}/></Button>}</div>}</section><section className="action-panel"><span className="small-tag">قدم بعدی</span><h2>{currentRole==='member'?'برای تمرین امروز آماده‌ای؟':'یک باشگاه منظم، یک تیم قوی‌تر.'}</h2><p>{currentRole==='member'?'برنامه اختصاصی خود را مرور کن و بعد از تمرین، انجام آن را ثبت کن.':'کارهای روزمره را سریع انجام بده و برای همراهی با اعضا وقت بیشتری بگذار.'}</p><div className="quick-actions">{(currentRole==='member'?[['programs','تمرین امروز',Dumbbell],['nutrition','برنامه غذایی',Utensils],['progress','ثبت پیشرفت',Target]]:isTrainer?[['programs','طراحی تمرین',Dumbbell],['progress','ثبت پیشرفت',Target],['members','اعضای من',Users]]:[['attendance','ثبت ورود',CalendarCheck],['memberships','تمدید عضویت',CreditCard],['payments','ثبت پرداخت',Plus]]).map(([key,label,Icon]:any)=><button key={key} onClick={()=>currentRole==='member'?go(key):open(key==='progress'?'measurements':key)}><Icon size={18}/>{label}<ArrowUpLeft size={16}/></button>)}</div></section></div>
 <div className="dashboard-grid lower"><section className="panel"><div className="panel-heading"><h2>{currentRole==='member'?'برنامه‌های من':'اعضای تازه‌وارد'}</h2><button className="text-btn" onClick={()=>go(currentRole==='member'?'programs':'members')}>مشاهده همه<ChevronLeft size={15}/></button></div>{currentRole==='member'?<ProgramCards programs={data.programs.slice(0,3)} memberName={memberName} onOpen={(r:Row)=>setDetail({type:'program',...r})}/>:<DataTable rows={members.slice(0,5)} columns={[["name","عضو",r=><div className="person"><div className="avatar">{r.name[0]}</div><div><b>{r.name}</b><span dir="ltr">{r.phone}</span></div></div>],["created_at","تاریخ عضویت",r=>date(r.created_at)],["status","وضعیت",r=><Status value={r.status}/>]]} onRow={r=>setDetail({type:'member',...r})}/>}</section><section className="panel"><div className="panel-heading"><h2>نیاز به توجه</h2><span className="count-label">{number(expiring.length+data.products.filter((p:Row)=>p.stock<=p.threshold).length)}</span></div>{!expiring.length&&!data.products.some((p:Row)=>p.stock<=p.threshold)?<div className="calm-state"><CheckCircle2 size={34}/><h3>همه چیز مرتب است</h3><p>یادآوری‌های تمدید و موجودی در این بخش قرار می‌گیرند.</p></div>:<div className="attention-list">{expiring.slice(0,4).map(m=><button key={m.id} onClick={()=>go('memberships')}><span className="attention-icon"><Clock size={18}/></span><div><b>{memberName(m.member_id)}</b><span>{number(daysLeft(m.end_date))} روز تا پایان عضویت</span></div><ChevronLeft size={16}/></button>)}{data.products.filter((p:Row)=>p.stock<=p.threshold).slice(0,3).map((p:Row)=><button key={p.id} onClick={()=>go('products')}><Package size={18}/><div><b>{p.name}</b><span>{number(p.stock)} عدد موجودی</span></div></button>)}</div>}</section></div>
 </>}
 {paged&&<div className="filterbar"><div className="search"><Search size={18}/><input placeholder="جست‌وجوی نام، شماره تماس یا مرجع…" aria-label="جست‌وجو" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{number(listing?.total??(data[collection]||[]).length)} رکورد</span>{view==='memberships'&&write('plans')&&<Button variant="secondary" onClick={()=>open('plans')}>تعریف پلن<Plus size={16}/></Button>}{view==='products'&&<Button variant="secondary" onClick={()=>open('cart')}>سبد خرید ({number(cart.reduce((s,p)=>s+p.quantity,0))})<ShoppingBag size={17}/></Button>}</div>}
 {view==='members'&&<section className="panel"><DataTable rows={filtered(members)} onRow={r=>setDetail({type:'member',...r})} columns={[["name","نام عضو",r=><div className="person"><div className="avatar">{r.name[0]}</div><div><b>{r.name}</b><span>{r.email||'ایمیل ثبت نشده'}</span></div></div>],["phone","تلفن",r=><span dir="ltr">{r.phone}</span>],["goal","هدف"],["branch_id","شعبه",r=>branchName(r.branch_id)],["status","وضعیت",r=><Status value={r.status}/>],["id","",r=><button className="text-btn" onClick={e=>{e.stopPropagation();setDetail({type:'member',...r})}}>پرونده<ChevronLeft size={15}/></button>]]}/></section>}
 {view==='memberships'&&<><div className="plan-grid">{data.plans.map((p:Row)=><div className="panel plan-card" key={p.id}><span className="small-tag">{number(p.duration)} روزه</span><h3>{p.name}</h3><strong>{money(p.price)}</strong><p>{p.description||'عضویت باشگاه'}</p><div className="row-between"><Status value={p.status}/>{write('plans')&&<button className="text-btn" onClick={()=>open('plans',p)}>ویرایش</button>}</div></div>)}</div><section className="panel"><DataTable rows={filtered(visible(data.memberships))} columns={[["member_id","عضو",r=>r.member_name||memberName(r.member_id)],["plan_id","پلن",r=>data.plans.find((p:Row)=>p.id===r.plan_id)?.name||'پلن'],["end_date","اعتبار",r=><div><b>{date(r.end_date)}</b><span className="cell-sub">از {date(r.start_date)}</span></div>],["days","روز باقی‌مانده",r=><div className="days-cell"><b>{number(Math.max(0,daysLeft(r.end_date)))}</b><Progress value={Math.min(100,Math.max(0,100*(daysLeft(r.end_date)+1)/(daysLeft(r.end_date,r.start_date)+1)))}/></div>],["status","وضعیت",r=><Status value={r.status}/>],["balance","مانده",r=>money(r.balance??getBalance(r,'membership_id'))],["actions","عملیات",r=>write('memberships')?<div className="inline-actions"><button onClick={()=>open('memberships',{member_id:r.member_id,plan_id:r.plan_id,start_date:r.end_date>=today()?new Date(Date.parse(r.end_date)+86400000).toISOString().slice(0,10):today()})}>تمدید</button><button onClick={()=>open('payments',{member_id:r.member_id,membership_id:r.id,kind:'MEMBERSHIP',amount:Math.max(0,r.balance??getBalance(r,'membership_id'))})}>پرداخت</button><button onClick={()=>act(`memberships/${r.id}`,'PATCH',{status:r.status==='SUSPENDED'?'ACTIVE':'SUSPENDED'}).catch(()=>{})}>{r.status==='SUSPENDED'?'فعال‌سازی':'تعلیق'}</button></div>:'—']]}/></section></>}
 {view==='attendance'&&<section className="panel"><div className="panel-heading"><h2>ورودهای ثبت‌شده</h2>{(currentRole==='member'||write('attendance'))&&<Button variant="secondary" onClick={()=>open(currentRole==='member'?'qrShow':'qrScan')}>{currentRole==='member'?'کد ورود من':'اسکن QR عضو'}</Button>}</div><DataTable rows={filtered(attendance)} columns={[["member_id","عضو",r=>r.member_name||memberName(r.member_id)],["day","تاریخ ورود",r=>date(r.day)],["created_at","ساعت ورود",r=>new Date(r.created_at+'Z').toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tehran'})],["branch_id","شعبه",r=>branchName(r.branch_id)],["method","روش",r=>r.method==='RECEPTION'?'پذیرش':r.method==='QR'?'اسکن QR':'عضو']]}/></section>}
 {['programs','nutrition'].includes(view)&&<><ProgramCards programs={data.programs.filter((p:Row)=>p.kind===(view==='nutrition'?'nutrition':'workout'))} memberName={memberName} onOpen={(r:Row)=>setDetail({type:'program',...r})}/>{view==='programs'&&write('exercises')&&<section className="panel mt"><div className="panel-heading"><h2>کتابخانه حرکات</h2><Button variant="secondary" onClick={()=>open('exercises')}><Plus size={16}/>حرکت جدید</Button></div><DataTable rows={data.exercises} columns={[["name","حرکت"],["muscle","عضله هدف"],["equipment","تجهیزات"],["video","آموزش",r=>r.video?<a href={r.video} target="_blank" rel="noopener noreferrer" className="text-btn">مشاهده ویدئو</a>:'—']]}/></section>}</>}
 {view==='progress'&&<><section className="panel chart-panel"><div className="panel-heading"><h2>مسیر تغییر وزن</h2><span className="muted">برای نمودار اختصاصی، پرونده عضو را باز کنید.</span></div>{currentRole==='member'&&data.measurements.length?<WeightChart measurements={data.measurements}/>:<Blank title="هر عدد، بخشی از مسیر است" description="با انتخاب عضو و ثبت اندازه‌گیری، سابقه پیشرفت در پرونده او ساخته می‌شود."/>}</section><section className="panel mt"><DataTable rows={visible(data.measurements)} columns={[["member_id","عضو",r=>r.member_name||memberName(r.member_id)],["date","تاریخ",r=>date(r.date)],["weight","وزن",r=>number(r.weight)+' kg'],["fat","چربی",r=>r.fat?number(r.fat)+'٪':'—'],["waist","دور کمر",r=>r.waist?number(r.waist)+' cm':'—']]}/></section>{currentRole==='member'&&<PhotoPanel data={data} tid={tid} memberId={access.member_id} upload={()=>open('photo',{member_id:access.member_id})}/>}</>}
 {view==='access'&&<section className="panel"><DataTable rows={filtered(data.access)} columns={[["name","نام همکار"],["email","حساب ورود",r=><span dir="ltr">{r.email}</span>],["role","سطح دسترسی",r=><Status value={r.role}/>],["branch_id","محدوده شعبه",r=>r.branch_id?branchName(r.branch_id):'همه شعبه‌ها'],["member_id","عضو مرتبط",r=>r.member_id?memberName(r.member_id):'—'],["actions","عملیات",r=>r.role!=='owner'?<div className="inline-actions"><button onClick={()=>open('access',r)}>ویرایش دسترسی</button>{r.role!=='revoked'&&<button onClick={()=>open('revokeAccess',r)}>لغو دسترسی</button>}</div>:'—']]}/><p className="panel-note">همکار با حساب تأییدشده مربوط به همین ایمیل وارد می‌شود. دسترسی مربی فقط شامل اعضای اختصاص‌یافته است.</p></section>}
 {view==='products'&&<div className="product-grid">{filtered(data.products).length?filtered(data.products).map((p:Row)=><article className="panel product-card" key={p.id}><div className="product-visual"><Package size={42}/><span>{p.category}</span><Status value={p.status}/></div><div className="product-info"><span className="eyebrow">{p.brand||p.sku}</span><h3>{p.name}</h3><p>{p.description||p.category}</p><div className="row-between"><b>{money(p.price)}</b><span className={p.stock<=p.threshold?'warning-text':'muted'}>{number(p.stock)} عدد</span></div><div className="product-actions"><Button variant="secondary" disabled={p.stock<1||p.status!=='ACTIVE'} onClick={()=>{setCart(cs=>{const exists=cs.find(c=>c.id===p.id);return exists?cs.map(c=>c.id===p.id?{...c,quantity:Math.min(c.quantity+1,p.stock)}:c):[...cs,{...p,quantity:1}]});toast.success('به سبد خرید اضافه شد')}}><Plus size={17}/>افزودن به سبد</Button>{write('products')&&<button className="text-btn" onClick={()=>open('products',p)}>ویرایش</button>}</div></div></article>):<Blank title="فروشگاه شما آماده چیدمان است" description="اولین محصول را با قیمت و موجودی واقعی ثبت کنید."/>}</div>}
 {view==='orders'&&<section className="panel"><DataTable rows={filtered(visible(data.orders))} columns={[["id","سفارش",r=><button className="text-btn" onClick={async()=>{try{const items=await api('order-items/'+r.id);setDetail({type:'order',...r,items})}catch(e){toast.error((e as Error).message)}}}>#{r.id.slice(0,8)}</button>],["member_id","عضو",r=>r.member_name||memberName(r.member_id)],["created_at","تاریخ",r=>date(r.created_at)],["total","مبلغ",r=>money(r.total)],["status","وضعیت",r=><Status value={r.status}/>],["actions","عملیات",r=>currentRole!=='member'&&write('orders')?<div className="inline-actions">{r.status==='PENDING'&&<><button onClick={()=>open('payments',{member_id:r.member_id,order_id:r.id,kind:'ORDER',amount:r.balance??getBalance(r,'order_id')})}>ثبت پرداخت</button><button onClick={()=>open('cancelOrder',r)}>لغو</button></>}{nextStatus[r.status]&&<button onClick={()=>act(`orders/${r.id}`,'PATCH',{status:nextStatus[r.status]}).catch(()=>{})}>{labels[nextStatus[r.status]]}</button>}</div>:'—']]}/></section>}
 {view==='payments'&&<section className="panel"><DataTable rows={filtered(payments)} columns={[["reference","شماره مرجع"],["member_id","عضو",r=>r.member_name||memberName(r.member_id)],["amount","مبلغ",r=>money(r.amount)],["kind","موضوع",r=>labels[r.kind]],["date","تاریخ",r=>date(r.date)],["status","وضعیت",r=><Status value={r.status}/>],["invoice","رسید",r=><button className="text-btn" onClick={()=>setDetail({type:'receipt',...r})}><FileText size={16}/>مشاهده</button>]]}/><p className="panel-note">رسیدها بیانگر پرداخت ثبت‌شده توسط پذیرش هستند. پرداخت آنلاین هنوز متصل نشده است.</p></section>}
 {paged&&<div className="page-controls"><span>{pageBusy?'در حال دریافت…':`${number(listing?.items?.length||0)} مورد در این صفحه`}</span><Pagination><PaginationContent><PaginationItem><PaginationLink aria-disabled={!history.length||pageBusy} onClick={()=>{if(!history.length||pageBusy)return;setCursor(history.at(-1)||'');setHistory(h=>h.slice(0,-1))}}>قبلی</PaginationLink></PaginationItem><PaginationItem><PaginationLink aria-disabled={!listing?.nextCursor||pageBusy} onClick={()=>{if(!listing?.nextCursor||pageBusy)return;setHistory(h=>[...h,cursor]);setCursor(listing.nextCursor)}}>بعدی</PaginationLink></PaginationItem></PaginationContent></Pagination></div>}
 {view==='reports'&&<ReportsView api={api} branch={branch}/>}
 {view==='crm'&&<section className="panel"><div className="panel-heading"><h2>پیگیری‌های حفظ اعضا</h2><Button variant="secondary" onClick={()=>act('automations-run','POST',{}).catch(()=>{})} disabled={busy}><RefreshCw size={16}/>بررسی اعضای غیرفعال</Button></div><DataTable rows={data.crm_tasks} columns={[["title","موضوع"],["member_id","عضو",r=>r.member_name||memberName(r.member_id)],["status","وضعیت",r=><Status value={r.status}/>],["action","",r=><button className="text-btn" onClick={()=>act(`crm_tasks/${r.id}`,'PATCH',{status:r.status==='OPEN'?'DONE':'OPEN'}).catch(()=>{})}>{r.status==='OPEN'?'انجام شد':'بازگشایی'}</button>]]}/></section>}
 {view==='automations'&&<section className="panel"><div className="panel-heading"><div><h2>قواعد پیگیری باشگاه</h2><p>بررسی بر اساس تاریخ و فعالیت واقعی اعضا</p></div><Button onClick={()=>act('automations-run','POST',{}).catch(()=>{})} disabled={busy}><Zap size={17}/>{busy?'در حال بررسی…':'اجرای بررسی'}</Button></div>{data.automations.map((a:Row)=><div className="automation-row" key={a.id}><div className="automation-icon"><Zap size={20}/></div><div><h3>{({expiry:'یادآوری پایان عضویت',inactive:'پیگیری عدم حضور',stock:'هشدار موجودی کالا',program:'پایان اعتبار برنامه'} as Row)[a.kind]}</h3><p>{({expiry:'۷ روز و ۱ روز قبل از پایان؛ اطلاع‌رسانی هنگام انقضا',inactive:'اطلاع به مربی بعد از ۷ روز؛ ایجاد پیگیری بعد از ۱۴ روز',stock:'اعلان به مدیر وقتی موجودی به حد هشدار می‌رسد',program:'اطلاع به مربی برای بازبینی و تمدید برنامه'} as Row)[a.kind]}</p></div><Switch aria-label="فعال بودن قاعده" checked={!!a.enabled} onCheckedChange={enabled=>act(`automations/${a.id}`,'PATCH',{enabled}).catch(()=>{})}/></div>)}<p className="panel-note">{boot.user.mode==='standalone'?'قواعد هر پنج دقیقه در پس‌زمینه بررسی می‌شوند.':'قواعد با «اجرای بررسی» اجرا می‌شوند.'} اعلان تکراری برای یک رویداد ساخته نمی‌شود.</p></section>}
 {view==='notifications'&&<section className="panel">{data.notifications.length?data.notifications.map((n:Row)=><div className={`notification-row ${!n.read_at?'unread':''}`} key={n.id}><div className="automation-icon"><Bell size={19}/></div><div><h3>{n.title}</h3><p>{n.body}</p><span className="muted">{date(n.created_at)}</span></div>{!n.read_at&&<button className="text-btn" onClick={()=>act(`notifications/${n.id}`,'PATCH',{}).catch(()=>{})}><Check size={17}/>خواندم</button>}</div>):<Blank title="اعلانی ندارید" description="خبرهای عضویت، برنامه و پرداخت شما در این بخش نمایش داده می‌شوند."/>}</section>}
 {view==='settings'&&<><div className="settings-grid"><section className="panel"><div className="panel-heading"><h2>فضای باشگاه</h2><Building2 size={22}/></div><div className="settings-content"><h3>{data.tenant.name}</h3><p>منطقه زمانی: تهران</p><p>واحد پول: تومان</p>{boot.user.mode==='standalone'?<p><a className="text-btn" href="/account">مدیریت حساب و رمز عبور</a></p>:<p>ورود با حساب تأییدشده ChatGPT</p>}<Status value={data.tenant.entitlements.plan}/><p>ظرفیت اعضا: {data.tenant.entitlements.memberLimit===100?'۱۰۰ عضو':'تا سقف عملیاتی پلن'}</p><Button variant="secondary" onClick={()=>open('newGym')}><Plus size={17}/>ایجاد باشگاه مستقل</Button></div></section><section className="panel"><div className="panel-heading"><h2>شعبه‌های باشگاه</h2><Button variant="secondary" onClick={()=>open('branches')}><Plus size={17}/>شعبه جدید</Button></div><DataTable rows={data.branches} columns={[["name","نام"],["address","نشانی"],["edit","",r=><button className="text-btn" onClick={()=>open('branches',r)}>ویرایش</button>]]}/></section></div><section className="panel mt"><div className="panel-heading"><h2>تاریخچه عملیات</h2></div><DataTable rows={data.audit_logs.slice(0,30)} columns={[["actor","کاربر"],["action","عملیات"],["created_at","تاریخ",r=>date(r.created_at)]]}/></section></>}
 {view==='platform'&&<section className="panel"><div className="panel-heading"><div><h2>باشگاه‌های سامانه</h2><p>تخصیص پلن توسط مدیر سامانه؛ بدون برداشت وجه</p></div></div><DataTable rows={platform} columns={[["name","باشگاه"],["members","اعضا",r=>number(r.members)],["plan","پلن",r=><Status value={r.plan}/>],["trial_until","دوره آزمایشی",r=>r.trial_until?date(r.trial_until):'—'],["action","تخصیص پلن",r=><Pick value={r.plan} options={['STARTER','PRO','ENTERPRISE'].map(p=>[p,labels[p]])} onChange={async plan=>{try{await api('platform','POST',{id:r.id,plan});setPlatform((await api('platform')).tenants);await refresh();toast.success('پلن به‌روزرسانی شد')}catch(e){toast.error((e as Error).message)}}}/>]]}/></section>}
 </>}
 <footer className="workspace-footer"><span>FitSpace · فضای رشد باشگاه شما</span><span>اطلاعات اختصاصی {data?.tenant?.name}</span></footer></div>
 {currentRole==='member'&&<nav className="mobile-bottom">{[['dashboard','خانه',LayoutDashboard],['programs','تمرین',Dumbbell],['nutrition','تغذیه',Utensils],['progress','پیشرفت',Activity],['products','فروشگاه',ShoppingBag],['members','پروفایل',UserRound]].filter(([key])=>key!=='products'||data?.tenant?.entitlements?.store).map(([key,label,Icon]:any)=><button className={view===key?'active':''} key={key} onClick={()=>go(key)}><Icon size={21}/>{label}</button>)}</nav>}
 </main>
 {modal&&['qrShow','qrScan'].includes(modal.type)&&<QrDialog mode={modal.type==='qrShow'?'show':'scan'} memberId={access.member_id} api={api} onClose={()=>setModal(null)} onDone={()=>{refresh();toast.success('ورود عضو ثبت شد')}}/>}
 {modal&&['cancelOrder','revokeAccess'].includes(modal.type)&&<AlertDialog open onOpenChange={o=>!o&&setModal(null)}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{modal.type==='revokeAccess'?'لغو دسترسی همکار':'لغو سفارش'}</AlertDialogTitle><AlertDialogDescription>{modal.type==='revokeAccess'?'دسترسی این حساب به باشگاه بسته می‌شود. سوابق کاری حفظ می‌شوند.':'موجودی رزروشده به فروشگاه برمی‌گردد. سفارش دارای پرداخت قابل لغو نیست.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>انصراف</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();try{await act((modal.type==='revokeAccess'?'access/':'orders/')+modal.record.id,'PATCH',modal.type==='revokeAccess'?{revoke:true}:{status:'CANCELLED'});setModal(null)}catch{}}}>{modal.type==='revokeAccess'?'لغو دسترسی':'لغو سفارش'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
 {modal&&data&&!['qrShow','qrScan','cancelOrder','revokeAccess'].includes(modal.type)&&<Editor api={api} key={modal.type+(modal.record?.id||'')} modal={modal} data={data} busy={busy} cart={cart} setCart={setCart} onClose={()=>setModal(null)} onCreateGym={createGym} onSave={async(type,body,id)=>{await act(type+(id?'/'+id:''),id?'PUT':'POST',body);setModal(null)}} onOrder={async mid=>{await act('orders','POST',{member_id:mid,idempotency:modal.idempotency||(modal.idempotency=crypto.randomUUID()),items:cart.map(p=>({product_id:p.id,quantity:p.quantity}))});setCart([]);setModal(null);go('orders')}} onCancelOrder={async id=>{await act('orders/'+id,'PATCH',{status:'CANCELLED'});setModal(null)}}/>}
 <Sheet open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><SheetContent side="left" className="detail-sheet" dir="rtl"><SheetHeader><SheetTitle>{detail?.name||detail?.title||({member:'پرونده عضو',program:'برنامه اختصاصی',order:'جزئیات سفارش',receipt:'رسید پرداخت'} as Row)[detail?.type]}</SheetTitle><SheetDescription>{detail?.type==='member'?'عضویت، فعالیت و مسیر پیشرفت':detail?.type==='receipt'?'رسید ثبت‌شده در پذیرش باشگاه':'اطلاعات ثبت‌شده باشگاه'}</SheetDescription></SheetHeader>{detail&&data&&<div className="detail-content">{detail.type==='member'&&<><div className="member-profile"><div className="avatar huge">{detail.name[0]}</div><h2>{detail.name}</h2><p dir="ltr">{detail.phone}</p><Status value={detail.status}/>{write('members')&&<Button variant="secondary" onClick={()=>open('members',detail)}>ویرایش مشخصات</Button>}</div><Tabs defaultValue="overview" dir="rtl"><TabsList className="w-full"><TabsTrigger value="overview">مشخصات</TabsTrigger><TabsTrigger value="progress">پیشرفت</TabsTrigger><TabsTrigger value="activity">فعالیت</TabsTrigger></TabsList><TabsContent value="overview"><dl className="profile-facts"><dt>هدف</dt><dd>{detail.goal||'—'}</dd><dt>ایمیل</dt><dd>{detail.email||'—'}</dd><dt>قد</dt><dd>{detail.height?number(detail.height)+' سانتی‌متر':'—'}</dd><dt>تماس اضطراری</dt><dd>{detail.emergency||'—'}</dd><dt>یادداشت</dt><dd>{detail.notes||'—'}</dd></dl><h3>عضویت‌ها</h3>{data.memberships.filter((m:Row)=>m.member_id===detail.id).map((m:Row)=><div key={m.id} className="mini-record"><Status value={m.status}/><span>تا {date(m.end_date)}</span></div>)}</TabsContent><TabsContent value="progress"><WeightChart measurements={data.measurements.filter((m:Row)=>m.member_id===detail.id)}/>{write('measurements')&&<Button variant="secondary" onClick={()=>open('measurements',{member_id:detail.id})}><Plus size={17}/>ثبت اندازه‌گیری</Button>}{can(currentRole,'photos')&&<PhotoPanel tid={tid} data={data} memberId={detail.id} upload={()=>open('photo',{member_id:detail.id})}/>}</TabsContent><TabsContent value="activity">{[...data.attendance.filter((a:Row)=>a.member_id===detail.id).map((a:Row)=>({...a,title:'ورود به باشگاه'})),...data.payments.filter((p:Row)=>p.member_id===detail.id).map((p:Row)=>({...p,title:'پرداخت '+money(p.amount)})),...data.programs.filter((p:Row)=>p.member_id===detail.id).map((p:Row)=>({...p,title:p.name}))].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,30).map(a=><div className="timeline-item" key={a.id}><CheckCircle2 size={16}/><div><b>{a.title}</b><span>{date(a.created_at)}</span></div></div>)}</TabsContent></Tabs></>}
 {detail.type==='program'&&<><div className="row-between"><Status value={detail.kind==='nutrition'?'برنامه غذایی':'برنامه تمرینی'}/>{write('programs')&&<Button variant="secondary" onClick={()=>open(detail.kind==='nutrition'?'nutrition':'programs',detail)}>ویرایش</Button>}</div><p className="muted">{detail.member_id?memberName(detail.member_id):'قالب قابل استفاده مجدد'}{detail.end_date&&' · تا '+date(detail.end_date)}</p>{detail.content.map((d:Row,i:number)=><section className="program-day" key={i}><h3>{d.day}</h3>{d.items.map((item:Row,j:number)=><div className="exercise" key={j}><span className="exercise-index">{number(j+1)}</span><div><h4>{item.name}</h4>{detail.kind==='workout'?<p>{item.sets&&number(item.sets)+' ست'} · {item.reps&&item.reps+' تکرار'} {item.weight&&' · '+item.weight+' کیلو'} {item.rest&&' · '+item.rest+' ثانیه استراحت'}</p>:<p>{item.time} · {number(item.calories)} کالری · پروتئین {number(item.protein)} گرم · کربوهیدرات {number(item.carbs)} · چربی {number(item.fat)}</p>}{item.notes&&<small>{item.notes}</small>}</div></div>)}{currentRole==='member'&&detail.kind==='workout'&&<Button variant="secondary" onClick={()=>act('workout_sessions','POST',{member_id:access.member_id,program_id:detail.id,day:d.day}).catch(()=>{})}><Check size={17}/>تمرین انجام شد</Button>}</section>)}</>}
 {detail.type==='order'&&<><Status value={detail.status}/><p>{memberName(detail.member_id)} · {date(detail.created_at)}</p>{detail.items.map((i:Row)=><div className="mini-record" key={i.id}><span>{i.name} × {number(i.quantity)}</span><b>{money(i.price*i.quantity)}</b></div>)}<div className="total-line"><span>مجموع</span><strong>{money(detail.total)}</strong></div></>}
 {detail.type==='receipt'&&<div className="receipt"><div className="brand">FitSpace.</div><h2>{data.tenant.name}</h2><CheckCircle2 size={40}/><h3>{money(detail.amount)}</h3><dl className="profile-facts"><dt>عضو</dt><dd>{memberName(detail.member_id)}</dd><dt>تاریخ</dt><dd>{date(detail.date)}</dd><dt>مرجع</dt><dd>{detail.reference}</dd><dt>موضوع</dt><dd>{labels[detail.kind]}</dd></dl><Button variant="secondary" onClick={()=>window.print()}><Download size={17}/>چاپ رسید</Button></div>}
 </div>}</SheetContent></Sheet>
 </SidebarProvider>
}
function Metric({label,value,suffix,Icon,accent=false,warning=false}:any){return <section className={`metric ${accent?'metric-accent':''}`}><div className="metric-top"><span>{label}</span><div className={warning?'warning-text':''}><Icon size={20}/></div></div><div className="metric-value"><strong>{value}</strong><span>{suffix}</span></div><div className="metric-bottom">{warning?'برای حفظ تداوم عضویت پیگیری کنید':accent?'اعضای دارای اعتبار در امروز':'بر اساس اطلاعات ثبت‌شده'}</div></section>}
function WeightChart({measurements}:any){if(!measurements.length)return <Blank title="اندازه‌گیری ثبت نشده" description="اولین اندازه‌گیری، نقطه شروع نمودار پیشرفت است."/>;return <div className="weight-chart"><ResponsiveContainer width="100%" height={240}><LineChart data={[...measurements].sort((a,b)=>a.date.localeCompare(b.date)).map(m=>({...m,label:date(m.date)}))}><CartesianGrid stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="label" fontSize={12}/><YAxis domain={['auto','auto']} width={32}/><Tooltip contentStyle={{background:'var(--card)',borderRadius:10}}/><Line type="monotone" dataKey="weight" name="وزن" stroke="#8cbb3d" strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></div>}
function ProgramCards({programs,memberName,onOpen}:any){return programs.length?<div className="program-grid">{programs.map((p:Row)=><button className="panel program-card" key={p.id} onClick={()=>onOpen(p)}><div className={`program-icon ${p.kind==='nutrition'?'nutrition':''}`}>{p.kind==='nutrition'?<Utensils size={25}/>:<Dumbbell size={25}/>}</div><span className="eyebrow">{p.kind==='nutrition'?'NUTRITION PLAN':'WORKOUT PLAN'}</span><h3>{p.name}</h3><p>{p.member_id?(p.member_name||memberName(p.member_id)):'قالب عمومی'}</p><div className="row-between"><span>{number(p.content.length)} {p.kind==='nutrition'?'وعده / بخش':'روز تمرین'}</span><ArrowUpLeft size={20}/></div></button>)}</div>:<Blank title="برنامه‌ای ثبت نشده" description="برنامه‌های تمرینی و غذایی اختصاصی اینجا در دسترس خواهند بود."/>}
function PhotoPanel({data,tid,memberId,upload}:any){return <section className="mt"><div className="panel-heading"><h3>تصاویر پیشرفت</h3><Button variant="secondary" onClick={upload}><Plus size={15}/>تصویر جدید</Button></div><div className="photo-grid">{data.photos.filter((p:Row)=>p.member_id===memberId).map((p:Row)=><figure key={p.id}><img src={`/api/gym/photo/${p.id}?tenant=${tid}`} alt={p.caption||'تصویر پیشرفت عضو'} loading="lazy"/><figcaption>{p.caption||date(p.created_at)}</figcaption></figure>)}</div></section>}
type EditorProps={api:(path:string)=>Promise<any>,modal:Row,data:Row,busy:boolean,cart:Row[],setCart:(v:any)=>void,onClose:()=>void,onCreateGym:(name:string)=>void,onSave:(type:string,body:any,id?:string)=>Promise<void>,onOrder:(id:string)=>Promise<void>,onCancelOrder:(id:string)=>Promise<void>};
function Editor({api,modal,data,busy,cart,setCart,onClose,onCreateGym,onSave,onOrder,onCancelOrder}:EditorProps){
 const type=modal.type,record=modal.record||{},editing=!!record.id&&!['cancelOrder','photo'].includes(type);const role=data.currentAccess.role;
 const [f,setF]=useState<Row>({name:'',member_id:role==='member'?data.currentAccess.member_id:'',branch_id:data.branches[0]?.id||data.members[0]?.branch_id||'',phone:'',email:'',status:'ACTIVE',duration:30,price:0,stock:0,threshold:5,kind:'MEMBERSHIP',date:today(),start_date:today(),reference:'',...record});
 const [err,setErr]=useState(''),[saving,setSaving]=useState(false),[file,setFile]=useState<File|null>(null);
 const emptyItem=()=>({name:'',sets:'3',reps:'12',rest:'60',weight:'',tempo:'',notes:'',calories:0,protein:0,carbs:0,fat:0,time:''});
 const [days,setDays]=useState<Row[]>(record.content||[{day:type==='nutrition'?'صبحانه':'روز اول',items:[emptyItem()]}]);
 const set=(key:string,value:any)=>setF(old=>({...old,[key]:value}));
 const titles:Row={members:'عضو باشگاه',plans:'پلن عضویت',memberships:'ثبت / تمدید عضویت',attendance:'ثبت ورود عضو',programs:'برنامه تمرینی',nutrition:'برنامه غذایی',measurements:'اندازه‌گیری جدید',access:'افزودن دسترسی',products:'محصول فروشگاه',payments:'ثبت رسید پرداخت',exercises:'حرکت ورزشی',branches:'شعبه باشگاه',notifications:'اعلان جدید',newGym:'باشگاه مستقل جدید',cart:'سبد خرید',photo:'تصویر پیشرفت',cancelOrder:'لغو سفارش'};
 const choices=(rows:Row[],name='name')=>rows.map(r=>[r.id,r[name]] as [string,string]);
 const memberPick=()=>role==='member'?null:<Field label="عضو"><EntityPicker api={api} table="members" value={f.member_id} onChange={v=>{set('member_id',v);set('order_id','');set('membership_id','')}} initial={data.members} required/></Field>;
 const inp=(key:string,label:string,inputType='text',required=false,extra:Row={})=><Field key={key} label={label}><input type={inputType} value={f[key]??''} onChange={e=>set(key,e.target.value)} required={required} aria-label={label} {...extra}/></Field>;
 const textarea=(key:string,label:string)=><Field label={label}><textarea value={f[key]||''} onChange={e=>set(key,e.target.value)} rows={3} maxLength={1000}/></Field>;
 const opts=(key:string,label:string,options:[string,string][],required=false)=>{const table=({member_id:'members',membership_id:'memberships',order_id:'orders',plan_id:'plans'} as Row)[key];return <Field label={label}>{table?<EntityPicker api={api} table={table} value={f[key]||''} onChange={v=>set(key,v)} initial={data[table]||[]} memberId={['orders','memberships'].includes(table)?f.member_id:''} required={required}/>:<Pick value={f[key]||''} onChange={v=>set(key,v)} options={options} required={required}/>}</Field>};
 async function submit(e:React.FormEvent){e.preventDefault();setErr('');setSaving(true);try{
  if(type==='newGym'){await onCreateGym(f.name);return}
  if(type==='cancelOrder'){await onCancelOrder(record.id);return}
  if(type==='cart'){if(!f.member_id)throw new Error('عضو را انتخاب کنید.');await onOrder(f.member_id);return}
  if(type==='photo'){if(!file)throw new Error('تصویر را انتخاب کنید.');const form=new FormData();form.set('file',file);form.set('member_id',f.member_id);form.set('caption',f.caption||'');await onSave('photos',form);return}
  let body={...f},resource=type;if(type==='products'&&editing)body.original_stock=record.stock;
  if(type==='programs'||type==='nutrition'){resource='programs';body={...f,kind:type==='nutrition'?'nutrition':'workout',content:days};}
  await onSave(resource,body,editing?record.id:undefined);
 }catch(e){setErr((e as Error).message)}finally{setSaving(false)}}
 const updateItem=(di:number,ii:number,key:string,value:any)=>setDays(ds=>ds.map((d,i)=>i===di?{...d,items:d.items.map((it:Row,j:number)=>j===ii?{...it,[key]:value}:it)}:d));
 return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent dir="rtl" className={`editor-dialog ${['programs','nutrition'].includes(type)?'wide':''}`}><DialogHeader><DialogTitle>{editing?'ویرایش ':''}{titles[type]}</DialogTitle><DialogDescription>{type==='cancelOrder'?'لغو سفارش پرداخت‌نشده، موجودی رزروشده را به فروشگاه برمی‌گرداند.':type==='payments'?'فقط پرداختی را ثبت کنید که واقعاً دریافت شده است.':type==='access'?'ایمیل حساب تأییدشده همکار یا عضو را وارد کنید.':'اطلاعات را وارد و ذخیره کنید.'}</DialogDescription></DialogHeader><form onSubmit={submit} className="editor-form"><div className="form-fields">
 {type==='newGym'&&inp('name','نام باشگاه','text',true,{maxLength:120})}
 {type==='members'&&<><div className="form-grid">{inp('name','نام و نام خانوادگی','text',true)}{inp('phone','شماره تماس','tel',true)}{inp('email','ایمیل','email')}{opts('branch_id','شعبه',choices(data.branches),true)}{inp('birth_date','تاریخ تولد','date')}{opts('gender','جنسیت',[['female','زن'],['male','مرد'],['undisclosed','ترجیح می‌دهم نگویم']])}{inp('height','قد (سانتی‌متر)','number',false,{min:0,max:260})}{inp('emergency','تماس اضطراری','tel')}{opts('trainer_id','مربی اختصاصی',choices(data.access.filter((a:Row)=>a.role==='trainer')))}{opts('level','سطح تجربه',[['مبتدی','مبتدی'],['متوسط','متوسط'],['پیشرفته','پیشرفته']])}</div>{inp('goal','هدف ورزشی')}{textarea('notes','یادداشت')}{opts('status','وضعیت',[['ACTIVE','فعال'],['INACTIVE','غیرفعال']])}</>}
 {type==='plans'&&<>{inp('name','نام پلن','text',true)}<div className="form-grid">{inp('duration','مدت اعتبار (روز)','number',true,{min:1,max:3650})}{inp('price','شهریه (تومان)','number',true,{min:0,step:1})}</div>{textarea('description','توضیحات')}{textarea('features','امکانات پلن')}{opts('status','وضعیت',[['ACTIVE','فعال'],['INACTIVE','غیرفعال']])}</>}
 {type==='memberships'&&<>{memberPick()}{opts('plan_id','پلن عضویت',choices(data.plans.filter((p:Row)=>p.status==='ACTIVE')),true)}{inp('start_date','شروع اعتبار (تاریخ میلادی)','date',true)}{f.plan_id&&<div className="form-summary"><span>شهریه</span><b>{money(data.plans.find((p:Row)=>p.id===f.plan_id)?.price||0)}</b><span>مدت اعتبار</span><b>{number(data.plans.find((p:Row)=>p.id===f.plan_id)?.duration)} روز</b></div>}<p className="muted">تمدید با بازه قبلی تداخل نخواهد داشت. ثبت عضویت به معنی دریافت وجه نیست.</p></>}
 {type==='attendance'&&<>{memberPick()}<div className="form-summary"><span>تاریخ ورود</span><b>{date(today())}</b></div><p className="muted">ورود فقط با عضویت فعال ثبت می‌شود. برای هر عضو یک ورود روزانه پذیرفته می‌شود.</p></>}
 {type==='access'&&<>{inp('name','نام همکار / عضو','text',true)}{inp('email','ایمیل حساب ورود','email',true)}{opts('role','سطح دسترسی',[['manager','مدیر'],['trainer','مربی'],['staff','پذیرش'],['member','عضو']],true)}{opts('branch_id','شعبه (اختیاری)',choices(data.branches))}{f.role==='member'&&memberPick()}<p className="muted">دسترسی مربی به اعضایی محدود است که در پرونده آن‌ها به‌عنوان مربی اختصاصی انتخاب شده باشد.</p></>}
 {type==='branches'&&<>{inp('name','نام شعبه','text',true)}{textarea('address','نشانی')}</>}
 {type==='exercises'&&<>{inp('name','نام حرکت','text',true)}{inp('muscle','عضله هدف')}{inp('equipment','تجهیزات')}{inp('video','لینک ویدئوی آموزش','url')}</>}
 {['programs','nutrition'].includes(type)&&<>{inp('name','نام برنامه','text',true)}<div className="form-grid">{role!=='member'&&<Field label="اختصاص به عضو (خالی = قالب)"><EntityPicker api={api} table="members" value={f.member_id} onChange={v=>set('member_id',v)} initial={data.members}/></Field>}{inp('end_date','پایان اعتبار (اختیاری)','date')}</div>{days.map((d,di)=><div className="builder-day" key={di}><div className="builder-day-head"><input aria-label="نام روز یا وعده" value={d.day} onChange={e=>setDays(ds=>ds.map((x,i)=>i===di?{...x,day:e.target.value}:x))} required/>{days.length>1&&<button type="button" className="icon-btn" aria-label="حذف روز" onClick={()=>setDays(ds=>ds.filter((_,i)=>i!==di))}><Trash2 size={17}/></button>}</div>{d.items.map((item:Row,ii:number)=><div className="builder-item" key={ii}><div className="builder-item-title"><span className="exercise-index">{number(ii+1)}</span><input aria-label={type==='nutrition'?'نام غذا':'نام حرکت'} placeholder={type==='nutrition'?'نام غذا یا مکمل':'نام حرکت'} required value={item.name} onChange={e=>updateItem(di,ii,'name',e.target.value)} list={type==='programs'?'exercise-library':undefined}/>{d.items.length>1&&<button type="button" className="icon-btn" aria-label="حذف آیتم" onClick={()=>setDays(ds=>ds.map((x,i)=>i===di?{...x,items:x.items.filter((_:any,j:number)=>j!==ii)}:x))}><X size={15}/></button>}</div><div className="builder-values">{(type==='nutrition'?[['time','ساعت'],['calories','کالری'],['protein','پروتئین (g)'],['carbs','کربوهیدرات (g)'],['fat','چربی (g)']]:[['sets','ست'],['reps','تکرار'],['weight','وزنه (kg)'],['rest','استراحت (s)'],['tempo','تمپو']]).map(([key,label])=><label key={key}><span>{label}</span><input aria-label={label} type={['calories','protein','carbs','fat'].includes(key)?'number':'text'} min="0" value={item[key]??''} onChange={e=>updateItem(di,ii,key,e.target.value)}/></label>)}</div><input aria-label="یادداشت مربی" placeholder="یادداشت مربی…" value={item.notes||''} onChange={e=>updateItem(di,ii,'notes',e.target.value)}/></div>)}<Button variant="secondary" onClick={()=>setDays(ds=>ds.map((x,i)=>i===di?{...x,items:[...x.items,emptyItem()]}:x))}><Plus size={16}/>{type==='nutrition'?'افزودن غذا':'افزودن حرکت'}</Button></div>)}<datalist id="exercise-library">{data.exercises.map((e:Row)=><option value={e.name} key={e.id}/>)}</datalist><Button variant="secondary" onClick={()=>setDays(ds=>[...ds,{day:type==='nutrition'?'وعده جدید':'روز '+number(ds.length+1),items:[emptyItem()]}])}><Plus size={16}/>{type==='nutrition'?'وعده جدید':'روز جدید'}</Button></>}
 {type==='measurements'&&<>{memberPick()}{inp('date','تاریخ اندازه‌گیری','date',true)}<div className="form-grid">{[['weight','وزن (kg)'],['fat','درصد چربی'],['chest','دور سینه (cm)'],['waist','دور کمر (cm)'],['arms','دور بازو (cm)'],['legs','دور ران (cm)'],['shoulders','دور شانه (cm)']].map(([key,label])=>inp(key,label,'number',key==='weight',{min:key==='weight'?1:0,step:.1}))}</div></>}
 {type==='products'&&<>{inp('name','نام محصول','text',true)}<div className="form-grid">{inp('sku','کد یکتای کالا (SKU)','text',true)}{inp('category','دسته‌بندی','text',true)}{inp('brand','برند')}{inp('price','قیمت (تومان)','number',true,{min:0,step:1})}{inp('stock','موجودی','number',true,{min:0,step:1})}{inp('threshold','حد هشدار موجودی','number',true,{min:0,step:1})}</div>{textarea('description','توضیحات')}{opts('status','وضعیت',[['ACTIVE','فعال'],['INACTIVE','غیرفعال']])}</>}
 {type==='payments'&&<>{memberPick()}{opts('kind','موضوع پرداخت',[['MEMBERSHIP','شهریه'],['ORDER','سفارش'],['PT','تمرین خصوصی'],['OTHER','سایر']],true)}{f.kind==='MEMBERSHIP'&&opts('membership_id','عضویت',data.memberships.filter((m:Row)=>m.member_id===f.member_id).map((m:Row)=>[m.id,(data.plans.find((p:Row)=>p.id===m.plan_id)?.name||'عضویت')+' — '+date(m.start_date)]),true)}{f.kind==='ORDER'&&opts('order_id','سفارش',data.orders.filter((o:Row)=>o.member_id===f.member_id&&o.status==='PENDING').map((o:Row)=>[o.id,'#'+o.id.slice(0,8)+' — '+money(o.total)]),true)}{inp('amount','مبلغ دریافت‌شده (تومان)','number',true,{min:1,step:1})}{inp('reference','شماره مرجع یکتا / رسید','text',true)}{inp('date','تاریخ پرداخت','date',true)}</>}
 {type==='notifications'&&<>{memberPick()}{inp('title','عنوان','text',true)}{textarea('body','متن اعلان')}</>}
 {type==='photo'&&<>{memberPick()}<Field label="تصویر (حداکثر ۵ مگابایت)"><input type="file" accept="image/jpeg,image/png,image/webp" required onChange={e=>setFile(e.target.files?.[0]||null)}/></Field>{inp('caption','توضیح تصویر')}</>}
 {type==='cart'&&<>{memberPick()}{cart.length?cart.map(p=><div className="cart-row" key={p.id}><div><b>{p.name}</b><span>{money(p.price)}</span></div><input aria-label={'تعداد '+p.name} type="number" min="1" max={p.stock} required value={p.quantity} onChange={e=>setCart((cs:Row[])=>cs.map(c=>c.id===p.id?{...c,quantity:Number(e.target.value)}:c))}/><button type="button" aria-label="حذف از سبد" className="icon-btn" onClick={()=>setCart((cs:Row[])=>cs.filter(c=>c.id!==p.id))}><Trash2 size={17}/></button></div>):<Blank title="سبد خرید خالی است" description="از فروشگاه، محصول انتخاب کنید."/>}<div className="total-line"><span>جمع سفارش</span><strong>{money(cart.reduce((s,p)=>s+p.price*p.quantity,0))}</strong></div><p className="muted">پس از ثبت، موجودی رزرو می‌شود. پرداخت در پذیرش باشگاه انجام می‌شود.</p></>}
 </div>{err&&<p className="form-error" role="alert">{err}</p>}<div className="editor-footer"><Button type="submit" disabled={busy||saving||(type==='cart'&&!cart.length)}>{busy||saving?'در حال ذخیره…':type==='cart'?'ثبت سفارش':type==='cancelOrder'?'لغو سفارش':'ذخیره اطلاعات'}<Check size={17}/></Button><Button variant="secondary" onClick={onClose}>بستن</Button></div></form></DialogContent></Dialog>
}
