'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Camera,RefreshCw,QrCode} from 'lucide-react';
export default function QrDialog({mode,memberId,api,onClose,onDone}:{mode:'show'|'scan',memberId?:string,api:(path:string,method?:string,body?:any)=>Promise<any>,onClose:()=>void,onDone:()=>void}){
 const [src,setSrc]=useState(''),[token,setToken]=useState(''),[expires,setExpires]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true),detected=useRef(false);
 const stop=()=>{if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};
 const issue=async()=>{setBusy(true);setError('');try{const r=await api('qr-issue','POST',{member_id:memberId});const QR=await import('qrcode');const img=await QR.toDataURL(r.token,{width:300,margin:3,errorCorrectionLevel:'M',color:{dark:'#17212b',light:'#ffffff'}});if(alive.current){setSrc(img);setToken(r.token);setExpires(r.expires)}}catch(e){if(alive.current)setError((e as Error).message)}finally{if(alive.current)setBusy(false)}};
 useEffect(()=>{alive.current=true;if(mode==='show')issue();return()=>{alive.current=false;stop()}},[]);
 const submit=async(value:string)=>{setBusy(true);setError('');stop();setCamera(false);try{const r=await api('qr-checkin','POST',{token:value});onDone();onClose()}catch(e){setError((e as Error).message);detected.current=false}finally{setBusy(false)}};
 const start=async()=>{setError('');detected.current=false;try{const Detector=(window as any).BarcodeDetector;if(!Detector)throw new Error('اسکن دوربین در این مرورگر پشتیبانی نمی‌شود. کد ورود را در کادر پایین وارد کنید.');const detector=new Detector({formats:['qr_code']});const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(!alive.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;setCamera(true);timer.current=setTimeout(async()=>{if(!video.current)return;video.current.srcObject=media;await video.current.play();const scan=async()=>{if(!alive.current||!stream.current||detected.current)return;try{const codes=await detector.detect(video.current);if(codes[0]){detected.current=true;await submit(codes[0].rawValue);return}}catch{}timer.current=setTimeout(scan,250)};scan()},100)}catch(e){stop();setCamera(false);setError((e as Error).message)}};
 return <Dialog open onOpenChange={o=>!o&&onClose()}><DialogContent className="editor-dialog" dir="rtl"><DialogHeader><DialogTitle>{mode==='show'?'کد ورود باشگاه':'ثبت ورود با QR'}</DialogTitle><DialogDescription>{mode==='show'?'کد را به پذیرش نشان دهید. اعتبار کد ۵ دقیقه است.':'کد عضو را اسکن یا متن کد را وارد کنید.'}</DialogDescription></DialogHeader>{mode==='show'?<div className="qr-display">{src?<img src={src} width={300} height={300} alt="کد QR ورود به باشگاه"/>:<QrCode size={100}/>}<p className="muted">{expires?'اعتبار تا '+new Date(expires).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'}):'در حال ساخت کد…'}</p>{token&&<input readOnly aria-label="متن کد برای پذیرش" value={token} dir="ltr" onFocus={e=>e.target.select()}/>}<button className="btn secondary" onClick={issue} disabled={busy}><RefreshCw size={17}/>ساخت کد جدید</button></div>:<><video ref={video} playsInline muted className={camera?'qr-camera':'hidden'}/><button className="btn secondary" type="button" onClick={start} disabled={busy||camera}><Camera size={18}/>فعال‌کردن دوربین</button><form onSubmit={e=>{e.preventDefault();submit(token)}} className="qr-input"><input value={token} onChange={e=>setToken(e.target.value)} placeholder="FITSPACE:…" dir="ltr" required aria-label="کد ورود عضو"/><button className="btn" disabled={busy||!token} type="submit">{busy?'در حال بررسی…':'ثبت ورود'}</button></form></>}{error&&<p role="alert" className="form-error">{error}</p>}</DialogContent></Dialog>
}
