'use client';
import {useEffect,useState} from 'react';
import {today} from '@/lib/gym/domain';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
export default function ReportsView({api,branch}:{api:(path:string)=>Promise<any>,branch:string}){
 const [from,setFrom]=useState(new Date(Date.parse(today())-13*86400000).toISOString().slice(0,10)),[to,setTo]=useState(today()),[report,setReport]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;setError('');setReport(null);api('report?'+new URLSearchParams({from,to,branch})).then(r=>{if(active)setReport(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[api,from,to,branch]);
 const download=async(table:string)=>{setBusy(true);setError('');try{let cursor='',all:any[]=[];do{const page=await api('page/'+table+'?'+new URLSearchParams({branch,...(table==='payments'?{from,to}:{}),cursor,limit:'100'}));all.push(...page.items);cursor=page.nextCursor||'';}while(cursor);if(!all.length)throw Error('رکوردی برای خروجی وجود ندارد.');const fields=table==='members'?['id','name','phone','email','status','branch_id','created_at']:['id','member_name','amount','kind','reference','date','status'];const escape=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv='\ufeff'+[fields.join(','),...all.map(r=>fields.map(k=>escape(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`fitspace-${table}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const num=(v:number=0)=>v.toLocaleString('fa-IR');
 return <section className="panel"><div className="panel-heading"><h2>گزارش کامل باشگاه</h2></div><div className="report-filters"><label className="field">از تاریخ<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">تا تاریخ<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn secondary" disabled={busy} onClick={()=>download('members')}>خروجی همه اعضا</button><button className="btn secondary" disabled={busy} onClick={()=>download('payments')}>{busy?'در حال آماده‌سازی…':'خروجی پرداخت‌های بازه'}</button></div>{error&&<p role="alert">{error}</p>}{report&&<><div className="stats-grid three"><div className="panel"><h3>درآمد بازه · تومان</h3><strong>{num(report.rangeRevenue)}</strong></div><div className="panel"><h3>مجموع ورودهای بازه</h3><strong>{num(report.rangeAttendance)}</strong></div><div className="panel"><h3>عضویت فعال امروز</h3><strong>{num(report.summary.active)}</strong></div></div><ResponsiveContainer width="100%" height={300}><BarChart data={report.daily}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="date" fontSize={11}/><YAxis fontSize={11}/><Tooltip/><Bar dataKey="revenue" name="درآمد (تومان)" fill="#a5cf5b"/></BarChart></ResponsiveContainer><p className="panel-note">گزارش از تمام رکوردهای مجاز محاسبه می‌شود. خروجی اعضا شامل همه اعضای شعبه انتخابی است؛ خروجی پرداخت‌ها تابع بازه تاریخ است. تغییر هم‌زمان داده‌ها هنگام دریافت CSV ممکن است روی نتیجه اثر بگذارد.</p></>}</section>
}
